-- Space-Time Smackdown (A2) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A2
-- Limitless lists Space-Time Smackdown as A2 with 207 cards.
-- Pack values are derived from the Limitless A2 pack filters:
-- Dialga, Palkia, and Shared.

insert into public.cards (id, name, pack, image)
select
  'A2-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2/A2_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Oddish', 'Shared'),
    (2, 'Gloom', 'Shared'),
    (3, 'Bellossom', 'Shared'),
    (4, 'Tangela', 'Dialga'),
    (5, 'Tangrowth', 'Dialga'),
    (6, 'Yanma', 'Dialga'),
    (7, 'Yanmega ex', 'Dialga'),
    (8, 'Roselia', 'Shared'),
    (9, 'Roserade', 'Shared'),
    (10, 'Turtwig', 'Palkia'),
    (11, 'Grotle', 'Palkia'),
    (12, 'Torterra', 'Palkia'),
    (13, 'Kricketot', 'Palkia'),
    (14, 'Kricketune', 'Palkia'),
    (15, 'Burmy', 'Shared'),
    (16, 'Wormadam', 'Shared'),
    (17, 'Combee', 'Dialga'),
    (18, 'Vespiquen', 'Dialga'),
    (19, 'Carnivine', 'Palkia'),
    (20, 'Leafeon', 'Dialga'),
    (21, 'Mow Rotom', 'Shared'),
    (22, 'Shaymin', 'Dialga'),
    (23, 'Magmar', 'Palkia'),
    (24, 'Magmortar', 'Palkia'),
    (25, 'Slugma', 'Shared'),
    (26, 'Magcargo', 'Shared'),
    (27, 'Chimchar', 'Palkia'),
    (28, 'Monferno', 'Palkia'),
    (29, 'Infernape ex', 'Palkia'),
    (30, 'Heat Rotom', 'Shared'),
    (31, 'Swinub', 'Dialga'),
    (32, 'Piloswine', 'Dialga'),
    (33, 'Mamoswine', 'Dialga'),
    (34, 'Regice', 'Palkia'),
    (35, 'Piplup', 'Palkia'),
    (36, 'Prinplup', 'Palkia'),
    (37, 'Empoleon', 'Palkia'),
    (38, 'Buizel', 'Shared'),
    (39, 'Floatzel', 'Shared'),
    (40, 'Shellos', 'Palkia'),
    (41, 'Gastrodon', 'Palkia'),
    (42, 'Finneon', 'Shared'),
    (43, 'Lumineon', 'Shared'),
    (44, 'Snover', 'Shared'),
    (45, 'Abomasnow', 'Shared'),
    (46, 'Glaceon', 'Palkia'),
    (47, 'Wash Rotom', 'Shared'),
    (48, 'Frost Rotom', 'Shared'),
    (49, 'Palkia ex', 'Palkia'),
    (50, 'Manaphy', 'Palkia'),
    (51, 'Magnemite', 'Shared'),
    (52, 'Magneton', 'Shared'),
    (53, 'Magnezone', 'Shared'),
    (54, 'Voltorb', 'Shared'),
    (55, 'Electrode', 'Shared'),
    (56, 'Electabuzz', 'Dialga'),
    (57, 'Electivire', 'Dialga'),
    (58, 'Shinx', 'Dialga'),
    (59, 'Luxio', 'Dialga'),
    (60, 'Luxray', 'Dialga'),
    (61, 'Pachirisu ex', 'Dialga'),
    (62, 'Rotom', 'Palkia'),
    (63, 'Togepi', 'Shared'),
    (64, 'Togetic', 'Shared'),
    (65, 'Togekiss', 'Shared'),
    (66, 'Misdreavus', 'Palkia'),
    (67, 'Mismagius ex', 'Palkia'),
    (68, 'Ralts', 'Dialga'),
    (69, 'Kirlia', 'Dialga'),
    (70, 'Duskull', 'Dialga'),
    (71, 'Dusclops', 'Dialga'),
    (72, 'Dusknoir', 'Dialga'),
    (73, 'Drifloon', 'Dialga'),
    (74, 'Drifblim', 'Dialga'),
    (75, 'Uxie', 'Shared'),
    (76, 'Mesprit', 'Shared'),
    (77, 'Azelf', 'Shared'),
    (78, 'Giratina', 'Palkia'),
    (79, 'Cresselia', 'Palkia'),
    (80, 'Rhyhorn', 'Palkia'),
    (81, 'Rhydon', 'Palkia'),
    (82, 'Rhyperior', 'Palkia'),
    (83, 'Gligar', 'Dialga'),
    (84, 'Gliscor', 'Dialga'),
    (85, 'Hitmontop', 'Dialga'),
    (86, 'Nosepass', 'Shared'),
    (87, 'Regirock', 'Shared'),
    (88, 'Cranidos', 'Dialga'),
    (89, 'Rampardos', 'Dialga'),
    (90, 'Wormadam', 'Dialga'),
    (91, 'Riolu', 'Dialga'),
    (92, 'Lucario', 'Dialga'),
    (93, 'Hippopotas', 'Palkia'),
    (94, 'Hippowdon', 'Palkia'),
    (95, 'Gallade ex', 'Dialga'),
    (96, 'Murkrow', 'Dialga'),
    (97, 'Honchkrow', 'Dialga'),
    (98, 'Sneasel', 'Palkia'),
    (99, 'Weavile ex', 'Palkia'),
    (100, 'Poochyena', 'Shared'),
    (101, 'Mightyena', 'Shared'),
    (102, 'Stunky', 'Dialga'),
    (103, 'Skuntank', 'Dialga'),
    (104, 'Spiritomb', 'Palkia'),
    (105, 'Skorupi', 'Shared'),
    (106, 'Drapion', 'Shared'),
    (107, 'Croagunk', 'Dialga'),
    (108, 'Toxicroak', 'Dialga'),
    (109, 'Darkrai', 'Dialga'),
    (110, 'Darkrai ex', 'Dialga'),
    (111, 'Skarmory', 'Shared'),
    (112, 'Registeel', 'Dialga'),
    (113, 'Shieldon', 'Palkia'),
    (114, 'Bastiodon', 'Palkia'),
    (115, 'Wormadam', 'Palkia'),
    (116, 'Bronzor', 'Dialga'),
    (117, 'Bronzong', 'Dialga'),
    (118, 'Probopass', 'Shared'),
    (119, 'Dialga ex', 'Dialga'),
    (120, 'Heatran', 'Dialga'),
    (121, 'Gible', 'Palkia'),
    (122, 'Gabite', 'Palkia'),
    (123, 'Garchomp', 'Palkia'),
    (124, 'Lickitung', 'Palkia'),
    (125, 'Lickilicky ex', 'Palkia'),
    (126, 'Eevee', 'Shared'),
    (127, 'Porygon', 'Palkia'),
    (128, 'Porygon2', 'Palkia'),
    (129, 'Porygon-Z', 'Palkia'),
    (130, 'Aipom', 'Shared'),
    (131, 'Ambipom', 'Shared'),
    (132, 'Starly', 'Palkia'),
    (133, 'Staravia', 'Palkia'),
    (134, 'Staraptor', 'Palkia'),
    (135, 'Bidoof', 'Dialga'),
    (136, 'Bibarel', 'Dialga'),
    (137, 'Buneary', 'Dialga'),
    (138, 'Lopunny', 'Dialga'),
    (139, 'Glameow', 'Palkia'),
    (140, 'Purugly', 'Palkia'),
    (141, 'Chatot', 'Palkia'),
    (142, 'Fan Rotom', 'Shared'),
    (143, 'Regigigas', 'Shared'),
    (144, 'Skull Fossil', 'Dialga'),
    (145, 'Armor Fossil', 'Palkia'),
    (146, 'Pokémon Communication', 'Dialga'),
    (147, 'Giant Cape', 'Dialga'),
    (148, 'Rocky Helmet', 'Palkia'),
    (149, 'Lum Berry', 'Palkia'),
    (150, 'Cyrus', 'Palkia'),
    (151, 'Team Galactic Grunt', 'Dialga'),
    (152, 'Cynthia', 'Palkia'),
    (153, 'Volkner', 'Dialga'),
    (154, 'Dawn', 'Dialga'),
    (155, 'Mars', 'Palkia'),
    (156, 'Tangrowth', 'Dialga'),
    (157, 'Combee', 'Dialga'),
    (158, 'Carnivine', 'Palkia'),
    (159, 'Shaymin', 'Dialga'),
    (160, 'Mamoswine', 'Dialga'),
    (161, 'Gastrodon', 'Palkia'),
    (162, 'Manaphy', 'Palkia'),
    (163, 'Shinx', 'Dialga'),
    (164, 'Rotom', 'Palkia'),
    (165, 'Drifloon', 'Dialga'),
    (166, 'Mesprit', 'Dialga'),
    (167, 'Giratina', 'Palkia'),
    (168, 'Cresselia', 'Palkia'),
    (169, 'Rhyperior', 'Palkia'),
    (170, 'Lucario', 'Dialga'),
    (171, 'Hippopotas', 'Palkia'),
    (172, 'Spiritomb', 'Palkia'),
    (173, 'Croagunk', 'Dialga'),
    (174, 'Heatran', 'Dialga'),
    (175, 'Garchomp', 'Palkia'),
    (176, 'Staraptor', 'Palkia'),
    (177, 'Bidoof', 'Dialga'),
    (178, 'Glameow', 'Palkia'),
    (179, 'Regigigas', 'Dialga'),
    (180, 'Yanmega ex', 'Dialga'),
    (181, 'Infernape ex', 'Palkia'),
    (182, 'Palkia ex', 'Palkia'),
    (183, 'Pachirisu ex', 'Dialga'),
    (184, 'Mismagius ex', 'Palkia'),
    (185, 'Gallade ex', 'Dialga'),
    (186, 'Weavile ex', 'Palkia'),
    (187, 'Darkrai ex', 'Dialga'),
    (188, 'Dialga ex', 'Dialga'),
    (189, 'Lickilicky ex', 'Palkia'),
    (190, 'Cyrus', 'Palkia'),
    (191, 'Team Galactic Grunt', 'Dialga'),
    (192, 'Cynthia', 'Palkia'),
    (193, 'Volkner', 'Dialga'),
    (194, 'Dawn', 'Dialga'),
    (195, 'Mars', 'Palkia'),
    (196, 'Yanmega ex', 'Dialga'),
    (197, 'Infernape ex', 'Palkia'),
    (198, 'Pachirisu ex', 'Dialga'),
    (199, 'Mismagius ex', 'Palkia'),
    (200, 'Gallade ex', 'Dialga'),
    (201, 'Weavile ex', 'Palkia'),
    (202, 'Darkrai ex', 'Dialga'),
    (203, 'Lickilicky ex', 'Palkia'),
    (204, 'Palkia ex', 'Palkia'),
    (205, 'Dialga ex', 'Dialga'),
    (206, 'Palkia ex', 'Shared'),
    (207, 'Dialga ex', 'Shared')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
