-- Triumphant Light (A2a) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A2a
-- Limitless lists Triumphant Light as A2a with 96 cards.
-- Triumphant Light has one booster pack, represented here as Arceus.

insert into public.cards (id, name, pack, image)
select
  'A2a-' || lpad(card_number::text, 3, '0') as id,
  name,
  'Arceus' as pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2a/A2a_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Heracross'),
    (2, 'Burmy'),
    (3, 'Mothim'),
    (4, 'Combee'),
    (5, 'Vespiquen'),
    (6, 'Cherubi'),
    (7, 'Cherrim'),
    (8, 'Cherrim'),
    (9, 'Carnivine'),
    (10, 'Leafeon ex'),
    (11, 'Houndour'),
    (12, 'Houndoom'),
    (13, 'Heatran'),
    (14, 'Marill'),
    (15, 'Azumarill'),
    (16, 'Barboach'),
    (17, 'Whiscash'),
    (18, 'Snorunt'),
    (19, 'Froslass'),
    (20, 'Snover'),
    (21, 'Abomasnow'),
    (22, 'Glaceon ex'),
    (23, 'Origin Forme Palkia'),
    (24, 'Phione'),
    (25, 'Pikachu'),
    (26, 'Raichu'),
    (27, 'Electrike'),
    (28, 'Manectric'),
    (29, 'Clefairy'),
    (30, 'Clefable'),
    (31, 'Gastly'),
    (32, 'Haunter'),
    (33, 'Gengar'),
    (34, 'Unown'),
    (35, 'Rotom'),
    (36, 'Sudowoodo'),
    (37, 'Phanpy'),
    (38, 'Donphan'),
    (39, 'Larvitar'),
    (40, 'Pupitar'),
    (41, 'Tyranitar'),
    (42, 'Nosepass'),
    (43, 'Meditite'),
    (44, 'Medicham'),
    (45, 'Gible'),
    (46, 'Gabite'),
    (47, 'Garchomp ex'),
    (48, 'Zubat'),
    (49, 'Golbat'),
    (50, 'Crobat'),
    (51, 'Croagunk'),
    (52, 'Toxicroak'),
    (53, 'Magnemite'),
    (54, 'Magneton'),
    (55, 'Magnezone'),
    (56, 'Mawile'),
    (57, 'Probopass ex'),
    (58, 'Bronzor'),
    (59, 'Bronzong'),
    (60, 'Origin Forme Dialga'),
    (61, 'Giratina'),
    (62, 'Eevee'),
    (63, 'Snorlax'),
    (64, 'Hoothoot'),
    (65, 'Noctowl'),
    (66, 'Starly'),
    (67, 'Staravia'),
    (68, 'Staraptor'),
    (69, 'Shaymin'),
    (70, 'Arceus'),
    (71, 'Arceus ex'),
    (72, 'Irida'),
    (73, 'Celestic Town Elder'),
    (74, 'Barry'),
    (75, 'Adaman'),
    (76, 'Houndoom'),
    (77, 'Marill'),
    (78, 'Unown'),
    (79, 'Sudowoodo'),
    (80, 'Magnemite'),
    (81, 'Shaymin'),
    (82, 'Leafeon ex'),
    (83, 'Glaceon ex'),
    (84, 'Garchomp ex'),
    (85, 'Probopass ex'),
    (86, 'Arceus ex'),
    (87, 'Irida'),
    (88, 'Celestic Town Elder'),
    (89, 'Barry'),
    (90, 'Adaman'),
    (91, 'Leafeon ex'),
    (92, 'Glaceon ex'),
    (93, 'Garchomp ex'),
    (94, 'Probopass ex'),
    (95, 'Arceus ex'),
    (96, 'Arceus ex')
) as card_seed(card_number, name)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
