-- Extradimensional Crisis (A3a) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A3a
-- Limitless lists Extradimensional Crisis as A3a with 103 cards.
-- Extradimensional Crisis has one booster pack, represented here as Extradimensional Crisis.

insert into public.cards (id, name, pack, image)
select
  'A3a-' || lpad(card_number::text, 3, '0') as id,
  name,
  'Extradimensional Crisis' as pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3a/A3a_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Petilil'),
    (2, 'Lilligant'),
    (3, 'Rowlet'),
    (4, 'Dartrix'),
    (5, 'Decidueye'),
    (6, 'Buzzwole ex'),
    (7, 'Pheromosa'),
    (8, 'Kartana'),
    (9, 'Blacephalon'),
    (10, 'Mantine'),
    (11, 'Carvanha'),
    (12, 'Sharpedo'),
    (13, 'Shinx'),
    (14, 'Luxio'),
    (15, 'Luxray'),
    (16, 'Blitzle'),
    (17, 'Zebstrika'),
    (18, 'Emolga'),
    (19, 'Tapu Koko ex'),
    (20, 'Xurkitree'),
    (21, 'Zeraora'),
    (22, 'Clefairy'),
    (23, 'Clefable'),
    (24, 'Phantump'),
    (25, 'Trevenant'),
    (26, 'Morelull'),
    (27, 'Shiinotic'),
    (28, 'Meditite'),
    (29, 'Medicham'),
    (30, 'Baltoy'),
    (31, 'Claydol'),
    (32, 'Rockruff'),
    (33, 'Lycanroc ex'),
    (34, 'Passimian'),
    (35, 'Sandygast'),
    (36, 'Palossand'),
    (37, 'Alolan Meowth'),
    (38, 'Alolan Persian'),
    (39, 'Sandile'),
    (40, 'Krokorok'),
    (41, 'Krookodile'),
    (42, 'Nihilego'),
    (43, 'Guzzlord ex'),
    (44, 'Poipole'),
    (45, 'Naganadel'),
    (46, 'Alolan Diglett'),
    (47, 'Alolan Dugtrio ex'),
    (48, 'Aron'),
    (49, 'Lairon'),
    (50, 'Aggron'),
    (51, 'Ferroseed'),
    (52, 'Ferrothorn'),
    (53, 'Stakataka'),
    (54, 'Lillipup'),
    (55, 'Herdier'),
    (56, 'Stoutland'),
    (57, 'Stufful'),
    (58, 'Bewear'),
    (59, 'Oranguru'),
    (60, 'Type: Null'),
    (61, 'Silvally'),
    (62, 'Celesteela'),
    (63, 'Beast Wall'),
    (64, 'Repel'),
    (65, 'Electrical Cord'),
    (66, 'Beastite'),
    (67, 'Gladion'),
    (68, 'Looker'),
    (69, 'Lusamine'),
    (70, 'Rowlet'),
    (71, 'Pheromosa'),
    (72, 'Blacephalon'),
    (73, 'Alolan Meowth'),
    (74, 'Silvally'),
    (75, 'Celesteela'),
    (76, 'Buzzwole ex'),
    (77, 'Tapu Koko ex'),
    (78, 'Lycanroc ex'),
    (79, 'Guzzlord ex'),
    (80, 'Alolan Dugtrio ex'),
    (81, 'Gladion'),
    (82, 'Looker'),
    (83, 'Lusamine'),
    (84, 'Tapu Koko ex'),
    (85, 'Lycanroc ex'),
    (86, 'Guzzlord ex'),
    (87, 'Alolan Dugtrio ex'),
    (88, 'Buzzwole ex'),
    (89, 'Growlithe'),
    (90, 'Arcanine'),
    (91, 'Froakie'),
    (92, 'Frogadier'),
    (93, 'Greninja'),
    (94, 'Jynx'),
    (95, 'Pidgey'),
    (96, 'Pidgeotto'),
    (97, 'Pidgeot'),
    (98, 'Aerodactyl'),
    (99, 'Celebi ex'),
    (100, 'Arcanine ex'),
    (101, 'Aerodactyl ex'),
    (102, 'Pidgeot ex'),
    (103, 'Nihilego')
) as card_seed(card_number, name)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
