-- Celestial Guardians (A3) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A3
-- Limitless lists Celestial Guardians as A3 with 239 cards.
-- Pack values are derived from the Limitless A3 pack filters:
-- Lunala, Solgaleo, and Shared.

insert into public.cards (id, name, pack, image)
select
  'A3-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3/A3_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Exeggcute', 'Lunala'),
    (2, 'Alolan Exeggutor', 'Lunala'),
    (3, 'Surskit', 'Shared'),
    (4, 'Masquerain', 'Shared'),
    (5, 'Maractus', 'Lunala'),
    (6, 'Karrablast', 'Shared'),
    (7, 'Phantump', 'Solgaleo'),
    (8, 'Trevenant', 'Solgaleo'),
    (9, 'Rowlet', 'Solgaleo'),
    (10, 'Rowlet', 'Lunala'),
    (11, 'Dartrix', 'Lunala'),
    (12, 'Decidueye ex', 'Lunala'),
    (13, 'Grubbin', 'Lunala'),
    (14, 'Fomantis', 'Shared'),
    (15, 'Lurantis', 'Shared'),
    (16, 'Morelull', 'Lunala'),
    (17, 'Shiinotic', 'Lunala'),
    (18, 'Bounsweet', 'Solgaleo'),
    (19, 'Steenee', 'Solgaleo'),
    (20, 'Tsareena', 'Solgaleo'),
    (21, 'Wimpod', 'Solgaleo'),
    (22, 'Golisopod', 'Solgaleo'),
    (23, 'Dhelmise ex', 'Solgaleo'),
    (24, 'Tapu Bulu', 'Solgaleo'),
    (25, 'Growlithe', 'Shared'),
    (26, 'Arcanine', 'Shared'),
    (27, 'Alolan Marowak', 'Lunala'),
    (28, 'Fletchinder', 'Solgaleo'),
    (29, 'Talonflame', 'Solgaleo'),
    (30, 'Litten', 'Solgaleo'),
    (31, 'Litten', 'Lunala'),
    (32, 'Torracat', 'Solgaleo'),
    (33, 'Incineroar ex', 'Solgaleo'),
    (34, 'Oricorio', 'Lunala'),
    (35, 'Salandit', 'Shared'),
    (36, 'Salazzle', 'Shared'),
    (37, 'Turtonator', 'Lunala'),
    (38, 'Alolan Sandshrew', 'Shared'),
    (39, 'Alolan Sandslash', 'Shared'),
    (40, 'Alolan Vulpix', 'Lunala'),
    (41, 'Alolan Ninetales', 'Lunala'),
    (42, 'Shellder', 'Solgaleo'),
    (43, 'Cloyster', 'Solgaleo'),
    (44, 'Lapras', 'Shared'),
    (45, 'Popplio', 'Lunala'),
    (46, 'Popplio', 'Solgaleo'),
    (47, 'Brionne', 'Lunala'),
    (48, 'Primarina', 'Lunala'),
    (49, 'Crabominable ex', 'Solgaleo'),
    (50, 'Wishiwashi', 'Lunala'),
    (51, 'Wishiwashi ex', 'Lunala'),
    (52, 'Dewpider', 'Solgaleo'),
    (53, 'Araquanid', 'Solgaleo'),
    (54, 'Pyukumuku', 'Lunala'),
    (55, 'Bruxish', 'Shared'),
    (56, 'Tapu Fini', 'Lunala'),
    (57, 'Pikachu', 'Solgaleo'),
    (58, 'Alolan Raichu ex', 'Solgaleo'),
    (59, 'Alolan Geodude', 'Solgaleo'),
    (60, 'Alolan Graveler', 'Solgaleo'),
    (61, 'Alolan Golem', 'Solgaleo'),
    (62, 'Helioptile', 'Shared'),
    (63, 'Heliolisk', 'Shared'),
    (64, 'Charjabug', 'Lunala'),
    (65, 'Vikavolt', 'Lunala'),
    (66, 'Oricorio', 'Solgaleo'),
    (67, 'Togedemaru', 'Lunala'),
    (68, 'Tapu Koko', 'Solgaleo'),
    (69, 'Mr. Mime', 'Solgaleo'),
    (70, 'Sableye', 'Shared'),
    (71, 'Spoink', 'Shared'),
    (72, 'Grumpig', 'Shared'),
    (73, 'Lunatone', 'Lunala'),
    (74, 'Shuppet', 'Shared'),
    (75, 'Banette', 'Shared'),
    (76, 'Oricorio', 'Solgaleo'),
    (77, 'Oricorio', 'Lunala'),
    (78, 'Cutiefly', 'Solgaleo'),
    (79, 'Ribombee', 'Solgaleo'),
    (80, 'Comfey', 'Solgaleo'),
    (81, 'Sandygast', 'Solgaleo'),
    (82, 'Palossand', 'Solgaleo'),
    (83, 'Mimikyu', 'Lunala'),
    (84, 'Tapu Lele', 'Lunala'),
    (85, 'Cosmog', 'Shared'),
    (86, 'Cosmoem', 'Shared'),
    (87, 'Lunala ex', 'Lunala'),
    (88, 'Necrozma', 'Lunala'),
    (89, 'Cubone', 'Lunala'),
    (90, 'Makuhita', 'Shared'),
    (91, 'Hariyama', 'Shared'),
    (92, 'Solrock', 'Solgaleo'),
    (93, 'Drilbur', 'Shared'),
    (94, 'Timburr', 'Lunala'),
    (95, 'Gurdurr', 'Lunala'),
    (96, 'Conkeldurr', 'Lunala'),
    (97, 'Crabrawler', 'Solgaleo'),
    (98, 'Rockruff', 'Lunala'),
    (99, 'Rockruff', 'Solgaleo'),
    (100, 'Lycanroc', 'Solgaleo'),
    (101, 'Lycanroc', 'Lunala'),
    (102, 'Mudbray', 'Solgaleo'),
    (103, 'Mudsdale', 'Solgaleo'),
    (104, 'Passimian ex', 'Lunala'),
    (105, 'Minior', 'Lunala'),
    (106, 'Alolan Rattata', 'Lunala'),
    (107, 'Alolan Raticate', 'Lunala'),
    (108, 'Alolan Meowth', 'Solgaleo'),
    (109, 'Alolan Persian', 'Solgaleo'),
    (110, 'Alolan Grimer', 'Lunala'),
    (111, 'Alolan Muk ex', 'Lunala'),
    (112, 'Absol', 'Lunala'),
    (113, 'Trubbish', 'Shared'),
    (114, 'Garbodor', 'Shared'),
    (115, 'Mareanie', 'Lunala'),
    (116, 'Toxapex', 'Lunala'),
    (117, 'Alolan Diglett', 'Shared'),
    (118, 'Alolan Dugtrio', 'Shared'),
    (119, 'Excadrill', 'Shared'),
    (120, 'Escavalier', 'Shared'),
    (121, 'Klefki', 'Solgaleo'),
    (122, 'Solgaleo ex', 'Solgaleo'),
    (123, 'Magearna', 'Solgaleo'),
    (124, 'Drampa', 'Solgaleo'),
    (125, 'Jangmo-o', 'Lunala'),
    (126, 'Hakamo-o', 'Lunala'),
    (127, 'Kommo-o', 'Lunala'),
    (128, 'Tauros', 'Shared'),
    (129, 'Skitty', 'Shared'),
    (130, 'Delcatty', 'Shared'),
    (131, 'Fletchling', 'Solgaleo'),
    (132, 'Hawlucha', 'Solgaleo'),
    (133, 'Pikipek', 'Shared'),
    (134, 'Trumbeak', 'Shared'),
    (135, 'Toucannon', 'Shared'),
    (136, 'Yungoos', 'Solgaleo'),
    (137, 'Gumshoos', 'Solgaleo'),
    (138, 'Stufful', 'Lunala'),
    (139, 'Bewear', 'Lunala'),
    (140, 'Oranguru', 'Lunala'),
    (141, 'Komala', 'Solgaleo'),
    (142, 'Big Malasada', 'Shared'),
    (143, 'Fishing Net', 'Lunala'),
    (144, 'Rare Candy', 'Shared'),
    (145, 'Rotom Dex', 'Solgaleo'),
    (146, 'Poison Barb', 'Lunala'),
    (147, 'Leaf Cape', 'Solgaleo'),
    (148, 'Acerola', 'Lunala'),
    (149, 'Ilima', 'Lunala'),
    (150, 'Kiawe', 'Lunala'),
    (151, 'Guzma', 'Lunala'),
    (152, 'Lana', 'Solgaleo'),
    (153, 'Sophocles', 'Solgaleo'),
    (154, 'Mallow', 'Solgaleo'),
    (155, 'Lillie', 'Solgaleo'),
    (156, 'Alolan Exeggutor', 'Lunala'),
    (157, 'Morelull', 'Lunala'),
    (158, 'Tsareena', 'Solgaleo'),
    (159, 'Tapu Bulu', 'Solgaleo'),
    (160, 'Alolan Marowak', 'Lunala'),
    (161, 'Turtonator', 'Lunala'),
    (162, 'Alolan Vulpix', 'Lunala'),
    (163, 'Pyukumuku', 'Lunala'),
    (164, 'Tapu Fini', 'Lunala'),
    (165, 'Oricorio', 'Solgaleo'),
    (166, 'Tapu Koko', 'Solgaleo'),
    (167, 'Cutiefly', 'Solgaleo'),
    (168, 'Comfey', 'Solgaleo'),
    (169, 'Sandygast', 'Solgaleo'),
    (170, 'Tapu Lele', 'Lunala'),
    (171, 'Cosmog', 'Lunala'),
    (172, 'Rockruff', 'Solgaleo'),
    (173, 'Mudsdale', 'Solgaleo'),
    (174, 'Minior', 'Lunala'),
    (175, 'Magearna', 'Solgaleo'),
    (176, 'Drampa', 'Solgaleo'),
    (177, 'Pikipek', 'Lunala'),
    (178, 'Bewear', 'Lunala'),
    (179, 'Komala', 'Solgaleo'),
    (180, 'Decidueye ex', 'Lunala'),
    (181, 'Dhelmise ex', 'Solgaleo'),
    (182, 'Incineroar ex', 'Solgaleo'),
    (183, 'Crabominable ex', 'Solgaleo'),
    (184, 'Wishiwashi ex', 'Lunala'),
    (185, 'Alolan Raichu ex', 'Solgaleo'),
    (186, 'Lunala ex', 'Lunala'),
    (187, 'Passimian ex', 'Lunala'),
    (188, 'Alolan Muk ex', 'Lunala'),
    (189, 'Solgaleo ex', 'Solgaleo'),
    (190, 'Acerola', 'Lunala'),
    (191, 'Ilima', 'Lunala'),
    (192, 'Kiawe', 'Lunala'),
    (193, 'Guzma', 'Lunala'),
    (194, 'Lana', 'Solgaleo'),
    (195, 'Sophocles', 'Solgaleo'),
    (196, 'Mallow', 'Solgaleo'),
    (197, 'Lillie', 'Solgaleo'),
    (198, 'Decidueye ex', 'Lunala'),
    (199, 'Dhelmise ex', 'Solgaleo'),
    (200, 'Incineroar ex', 'Solgaleo'),
    (201, 'Crabominable ex', 'Solgaleo'),
    (202, 'Wishiwashi ex', 'Lunala'),
    (203, 'Alolan Raichu ex', 'Solgaleo'),
    (204, 'Lunala ex', 'Lunala'),
    (205, 'Passimian ex', 'Lunala'),
    (206, 'Alolan Muk ex', 'Lunala'),
    (207, 'Solgaleo ex', 'Solgaleo'),
    (208, 'Guzma', 'Lunala'),
    (209, 'Lillie', 'Solgaleo'),
    (210, 'Bulbasaur', 'Solgaleo'),
    (211, 'Ivysaur', 'Solgaleo'),
    (212, 'Venusaur', 'Solgaleo'),
    (213, 'Exeggcute', 'Lunala'),
    (214, 'Exeggutor', 'Lunala'),
    (215, 'Squirtle', 'Lunala'),
    (216, 'Wartortle', 'Lunala'),
    (217, 'Blastoise', 'Lunala'),
    (218, 'Staryu', 'Solgaleo'),
    (219, 'Starmie', 'Solgaleo'),
    (220, 'Gastly', 'Lunala'),
    (221, 'Haunter', 'Lunala'),
    (222, 'Gengar', 'Lunala'),
    (223, 'Machop', 'Solgaleo'),
    (224, 'Machoke', 'Solgaleo'),
    (225, 'Machamp', 'Solgaleo'),
    (226, 'Cubone', 'Lunala'),
    (227, 'Marowak', 'Lunala'),
    (228, 'Jigglypuff', 'Solgaleo'),
    (229, 'Wigglytuff', 'Solgaleo'),
    (230, 'Venusaur ex', 'Solgaleo'),
    (231, 'Exeggutor ex', 'Lunala'),
    (232, 'Blastoise ex', 'Lunala'),
    (233, 'Starmie ex', 'Solgaleo'),
    (234, 'Gengar ex', 'Lunala'),
    (235, 'Machamp ex', 'Solgaleo'),
    (236, 'Marowak ex', 'Lunala'),
    (237, 'Wigglytuff ex', 'Solgaleo'),
    (238, 'Lunala ex', 'Shared'),
    (239, 'Solgaleo ex', 'Shared')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
