-- Wisdom of Sea and Sky (A4) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A4
-- Limitless lists Wisdom of Sea and Sky as A4 with 241 cards.
-- Pack values are derived from the Limitless A4 pack filters:
-- Ho-Oh, Lugia, and Shared.

insert into public.cards (id, name, pack, image)
select
  'A4-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A4/A4_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Oddish', 'Lugia'),
    (2, 'Gloom', 'Lugia'),
    (3, 'Bellossom', 'Lugia'),
    (4, 'Tangela', 'Ho-Oh'),
    (5, 'Tangrowth', 'Ho-Oh'),
    (6, 'Scyther', 'Lugia'),
    (7, 'Pinsir', 'Lugia'),
    (8, 'Chikorita', 'Lugia'),
    (9, 'Bayleef', 'Lugia'),
    (10, 'Meganium', 'Lugia'),
    (11, 'Ledyba', 'Lugia'),
    (12, 'Ledian', 'Lugia'),
    (13, 'Hoppip', 'Ho-Oh'),
    (14, 'Skiploom', 'Ho-Oh'),
    (15, 'Jumpluff', 'Ho-Oh'),
    (16, 'Sunkern', 'Shared'),
    (17, 'Sunflora', 'Shared'),
    (18, 'Yanma', 'Shared'),
    (19, 'Yanmega', 'Shared'),
    (20, 'Pineco', 'Shared'),
    (21, 'Shuckle ex', 'Lugia'),
    (22, 'Heracross', 'Ho-Oh'),
    (23, 'Cherubi', 'Shared'),
    (24, 'Cherrim', 'Shared'),
    (25, 'Vulpix', 'Lugia'),
    (26, 'Ninetales', 'Lugia'),
    (27, 'Cyndaquil', 'Lugia'),
    (28, 'Quilava', 'Lugia'),
    (29, 'Typhlosion', 'Lugia'),
    (30, 'Slugma', 'Ho-Oh'),
    (31, 'Magcargo', 'Ho-Oh'),
    (32, 'Magby', 'Ho-Oh'),
    (33, 'Entei', 'Ho-Oh'),
    (34, 'Ho-Oh ex', 'Ho-Oh'),
    (35, 'Darumaka', 'Shared'),
    (36, 'Darmanitan', 'Shared'),
    (37, 'Heatmor', 'Shared'),
    (38, 'Poliwag', 'Lugia'),
    (39, 'Poliwhirl', 'Lugia'),
    (40, 'Politoed', 'Lugia'),
    (41, 'Horsea', 'Lugia'),
    (42, 'Seadra', 'Lugia'),
    (43, 'Kingdra ex', 'Lugia'),
    (44, 'Magikarp', 'Lugia'),
    (45, 'Gyarados', 'Lugia'),
    (46, 'Totodile', 'Ho-Oh'),
    (47, 'Croconaw', 'Ho-Oh'),
    (48, 'Feraligatr', 'Ho-Oh'),
    (49, 'Marill', 'Ho-Oh'),
    (50, 'Azumarill', 'Ho-Oh'),
    (51, 'Wooper', 'Lugia'),
    (52, 'Quagsire', 'Lugia'),
    (53, 'Qwilfish', 'Lugia'),
    (54, 'Corsola', 'Lugia'),
    (55, 'Remoraid', 'Lugia'),
    (56, 'Octillery', 'Lugia'),
    (57, 'Delibird', 'Ho-Oh'),
    (58, 'Mantine', 'Lugia'),
    (59, 'Suicune', 'Lugia'),
    (60, 'Corphish', 'Lugia'),
    (61, 'Crawdaunt', 'Lugia'),
    (62, 'Ducklett', 'Ho-Oh'),
    (63, 'Swanna', 'Ho-Oh'),
    (64, 'Chinchou', 'Lugia'),
    (65, 'Lanturn ex', 'Lugia'),
    (66, 'Pichu', 'Lugia'),
    (67, 'Mareep', 'Lugia'),
    (68, 'Flaaffy', 'Lugia'),
    (69, 'Ampharos', 'Lugia'),
    (70, 'Elekid', 'Lugia'),
    (71, 'Raikou', 'Ho-Oh'),
    (72, 'Emolga', 'Shared'),
    (73, 'Slowpoke', 'Lugia'),
    (74, 'Slowking', 'Lugia'),
    (75, 'Smoochum', 'Ho-Oh'),
    (76, 'Jynx', 'Shared'),
    (77, 'Cleffa', 'Lugia'),
    (78, 'Togepi', 'Ho-Oh'),
    (79, 'Togetic', 'Ho-Oh'),
    (80, 'Togekiss', 'Ho-Oh'),
    (81, 'Natu', 'Lugia'),
    (82, 'Xatu', 'Lugia'),
    (83, 'Espeon ex', 'Lugia'),
    (84, 'Unown', 'Ho-Oh'),
    (85, 'Unown', 'Lugia'),
    (86, 'Wobbuffet', 'Lugia'),
    (87, 'Girafarig', 'Ho-Oh'),
    (88, 'Snubbull', 'Shared'),
    (89, 'Granbull', 'Shared'),
    (90, 'Munna', 'Shared'),
    (91, 'Musharna', 'Shared'),
    (92, 'Onix', 'Ho-Oh'),
    (93, 'Sudowoodo', 'Shared'),
    (94, 'Gligar', 'Ho-Oh'),
    (95, 'Gliscor', 'Ho-Oh'),
    (96, 'Swinub', 'Ho-Oh'),
    (97, 'Piloswine', 'Ho-Oh'),
    (98, 'Mamoswine', 'Ho-Oh'),
    (99, 'Phanpy', 'Ho-Oh'),
    (100, 'Donphan ex', 'Ho-Oh'),
    (101, 'Tyrogue', 'Ho-Oh'),
    (102, 'Hitmontop', 'Shared'),
    (103, 'Larvitar', 'Ho-Oh'),
    (104, 'Pupitar', 'Ho-Oh'),
    (105, 'Binacle', 'Lugia'),
    (106, 'Barbaracle', 'Lugia'),
    (107, 'Zubat', 'Ho-Oh'),
    (108, 'Golbat', 'Ho-Oh'),
    (109, 'Crobat ex', 'Ho-Oh'),
    (110, 'Spinarak', 'Ho-Oh'),
    (111, 'Ariados', 'Ho-Oh'),
    (112, 'Umbreon ex', 'Ho-Oh'),
    (113, 'Murkrow', 'Lugia'),
    (114, 'Honchkrow', 'Lugia'),
    (115, 'Sneasel', 'Lugia'),
    (116, 'Weavile', 'Lugia'),
    (117, 'Houndour', 'Shared'),
    (118, 'Houndoom', 'Shared'),
    (119, 'Tyranitar', 'Ho-Oh'),
    (120, 'Absol', 'Shared'),
    (121, 'Forretress', 'Shared'),
    (122, 'Steelix', 'Ho-Oh'),
    (123, 'Scizor', 'Lugia'),
    (124, 'Skarmory ex', 'Ho-Oh'),
    (125, 'Mawile', 'Shared'),
    (126, 'Klink', 'Ho-Oh'),
    (127, 'Klang', 'Ho-Oh'),
    (128, 'Klinklang', 'Ho-Oh'),
    (129, 'Spearow', 'Ho-Oh'),
    (130, 'Fearow', 'Ho-Oh'),
    (131, 'Chansey', 'Ho-Oh'),
    (132, 'Blissey', 'Ho-Oh'),
    (133, 'Kangaskhan', 'Ho-Oh'),
    (134, 'Eevee', 'Shared'),
    (135, 'Porygon', 'Lugia'),
    (136, 'Porygon2', 'Lugia'),
    (137, 'Porygon-Z', 'Lugia'),
    (138, 'Sentret', 'Ho-Oh'),
    (139, 'Furret', 'Ho-Oh'),
    (140, 'Hoothoot', 'Ho-Oh'),
    (141, 'Noctowl', 'Ho-Oh'),
    (142, 'Aipom', 'Shared'),
    (143, 'Ambipom', 'Shared'),
    (144, 'Dunsparce', 'Shared'),
    (145, 'Teddiursa', 'Ho-Oh'),
    (146, 'Ursaring', 'Ho-Oh'),
    (147, 'Stantler', 'Ho-Oh'),
    (148, 'Smeargle', 'Lugia'),
    (149, 'Lugia ex', 'Lugia'),
    (150, 'Bouffalant', 'Shared'),
    (151, 'Elemental Switch', 'Lugia'),
    (152, 'Squirt Bottle', 'Lugia'),
    (153, 'Steel Apron', 'Ho-Oh'),
    (154, 'Dark Pendant', 'Ho-Oh'),
    (155, 'Rescue Scarf', 'Shared'),
    (156, 'Will', 'Lugia'),
    (157, 'Lyra', 'Lugia'),
    (158, 'Silver', 'Ho-Oh'),
    (159, 'Fisher', 'Lugia'),
    (160, 'Jasmine', 'Ho-Oh'),
    (161, 'Hiker', 'Ho-Oh'),
    (162, 'Chikorita', 'Lugia'),
    (163, 'Bellossom', 'Lugia'),
    (164, 'Heracross', 'Ho-Oh'),
    (165, 'Cyndaquil', 'Lugia'),
    (166, 'Magby', 'Ho-Oh'),
    (167, 'Totodile', 'Ho-Oh'),
    (168, 'Qwilfish', 'Lugia'),
    (169, 'Octillery', 'Lugia'),
    (170, 'Delibird', 'Ho-Oh'),
    (171, 'Pichu', 'Lugia'),
    (172, 'Ampharos', 'Lugia'),
    (173, 'Togepi', 'Ho-Oh'),
    (174, 'Xatu', 'Lugia'),
    (175, 'Wobbuffet', 'Lugia'),
    (176, 'Gligar', 'Ho-Oh'),
    (177, 'Spinarak', 'Ho-Oh'),
    (178, 'Murkrow', 'Lugia'),
    (179, 'Tyranitar', 'Ho-Oh'),
    (180, 'Scizor', 'Lugia'),
    (181, 'Sentret', 'Ho-Oh'),
    (182, 'Hoothoot', 'Ho-Oh'),
    (183, 'Stantler', 'Ho-Oh'),
    (184, 'Smeargle', 'Lugia'),
    (185, 'Blissey', 'Ho-Oh'),
    (186, 'Shuckle ex', 'Lugia'),
    (187, 'Ho-Oh ex', 'Ho-Oh'),
    (188, 'Kingdra ex', 'Lugia'),
    (189, 'Lanturn ex', 'Lugia'),
    (190, 'Espeon ex', 'Lugia'),
    (191, 'Donphan ex', 'Ho-Oh'),
    (192, 'Crobat ex', 'Ho-Oh'),
    (193, 'Umbreon ex', 'Ho-Oh'),
    (194, 'Skarmory ex', 'Ho-Oh'),
    (195, 'Lugia ex', 'Lugia'),
    (196, 'Will', 'Lugia'),
    (197, 'Lyra', 'Lugia'),
    (198, 'Silver', 'Ho-Oh'),
    (199, 'Fisher', 'Lugia'),
    (200, 'Jasmine', 'Ho-Oh'),
    (201, 'Hiker', 'Ho-Oh'),
    (202, 'Shuckle ex', 'Lugia'),
    (203, 'Kingdra ex', 'Lugia'),
    (204, 'Lanturn ex', 'Lugia'),
    (205, 'Espeon ex', 'Lugia'),
    (206, 'Donphan ex', 'Ho-Oh'),
    (207, 'Crobat ex', 'Ho-Oh'),
    (208, 'Umbreon ex', 'Ho-Oh'),
    (209, 'Skarmory ex', 'Ho-Oh'),
    (210, 'Ho-Oh ex', 'Ho-Oh'),
    (211, 'Lugia ex', 'Lugia'),
    (212, 'Yanma', 'Ho-Oh'),
    (213, 'Flareon', 'Ho-Oh'),
    (214, 'Magikarp', 'Lugia'),
    (215, 'Gyarados', 'Lugia'),
    (216, 'Vaporeon', 'Lugia'),
    (217, 'Magnemite', 'Lugia'),
    (218, 'Magneton', 'Lugia'),
    (219, 'Jolteon', 'Lugia'),
    (220, 'Misdreavus', 'Ho-Oh'),
    (221, 'Mankey', 'Ho-Oh'),
    (222, 'Primeape', 'Ho-Oh'),
    (223, 'Nidoran♀', 'Lugia'),
    (224, 'Nidorina', 'Lugia'),
    (225, 'Nidoqueen', 'Lugia'),
    (226, 'Nidoran♂', 'Ho-Oh'),
    (227, 'Nidorino', 'Ho-Oh'),
    (228, 'Nidoking', 'Ho-Oh'),
    (229, 'Sneasel', 'Lugia'),
    (230, 'Lickitung', 'Ho-Oh'),
    (231, 'Eevee', 'Ho-Oh'),
    (232, 'Yanmega ex', 'Ho-Oh'),
    (233, 'Leafeon ex', 'Ho-Oh'),
    (234, 'Gyarados ex', 'Lugia'),
    (235, 'Glaceon ex', 'Lugia'),
    (236, 'Pachirisu ex', 'Lugia'),
    (237, 'Mismagius ex', 'Ho-Oh'),
    (238, 'Weavile ex', 'Lugia'),
    (239, 'Lickilicky ex', 'Ho-Oh'),
    (240, 'Ho-Oh ex', 'Shared'),
    (241, 'Lugia ex', 'Shared')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
