-- Mega Rising (B1) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B1
-- Limitless lists Mega Rising as B1 with 331 cards.
-- Pack values are derived from the Limitless B1 pack filters:
-- Mega Altaria, Mega Blaziken, Mega Gyarados, and Shared.

insert into public.cards (id, name, pack, image)
select
  'B1-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1/B1_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Pinsir', 'Mega Blaziken'),
    (2, 'Mega Pinsir ex', 'Mega Blaziken'),
    (3, 'Wurmple', 'Mega Blaziken'),
    (4, 'Silcoon', 'Mega Blaziken'),
    (5, 'Beautifly', 'Mega Blaziken'),
    (6, 'Cascoon', 'Mega Blaziken'),
    (7, 'Dustox', 'Mega Blaziken'),
    (8, 'Seedot', 'Mega Blaziken'),
    (9, 'Nuzleaf', 'Mega Blaziken'),
    (10, 'Shiftry', 'Mega Blaziken'),
    (11, 'Shroomish', 'Shared'),
    (12, 'Breloom', 'Shared'),
    (13, 'Pansage', 'Mega Gyarados'),
    (14, 'Simisage', 'Mega Gyarados'),
    (15, 'Cottonee', 'Mega Altaria'),
    (16, 'Whimsicott ex', 'Mega Altaria'),
    (17, 'Petilil', 'Mega Altaria'),
    (18, 'Lilligant', 'Mega Altaria'),
    (19, 'Maractus', 'Shared'),
    (20, 'Virizion', 'Mega Altaria'),
    (21, 'Skiddo', 'Mega Altaria'),
    (22, 'Gogoat', 'Mega Altaria'),
    (23, 'Phantump', 'Shared'),
    (24, 'Trevenant', 'Shared'),
    (25, 'Grookey', 'Mega Altaria'),
    (26, 'Thwackey', 'Mega Altaria'),
    (27, 'Rillaboom', 'Mega Altaria'),
    (28, 'Growlithe', 'Mega Blaziken'),
    (29, 'Arcanine', 'Mega Blaziken'),
    (30, 'Ponyta', 'Mega Blaziken'),
    (31, 'Rapidash ex', 'Mega Blaziken'),
    (32, 'Ho-Oh', 'Mega Blaziken'),
    (33, 'Torchic', 'Mega Blaziken'),
    (34, 'Combusken', 'Mega Blaziken'),
    (35, 'Blaziken', 'Mega Blaziken'),
    (36, 'Mega Blaziken ex', 'Mega Blaziken'),
    (37, 'Pansear', 'Mega Blaziken'),
    (38, 'Simisear', 'Mega Blaziken'),
    (39, 'Darumaka', 'Mega Gyarados'),
    (40, 'Darmanitan', 'Mega Gyarados'),
    (41, 'Litwick', 'Mega Altaria'),
    (42, 'Lampent', 'Mega Altaria'),
    (43, 'Chandelure', 'Mega Altaria'),
    (44, 'Heatmor', 'Shared'),
    (45, 'Litleo', 'Mega Blaziken'),
    (46, 'Pyroar', 'Mega Blaziken'),
    (47, 'Turtonator', 'Mega Gyarados'),
    (48, 'Psyduck', 'Mega Blaziken'),
    (49, 'Golduck', 'Mega Blaziken'),
    (50, 'Magikarp', 'Mega Gyarados'),
    (51, 'Gyarados', 'Mega Gyarados'),
    (52, 'Mega Gyarados ex', 'Mega Gyarados'),
    (53, 'Lotad', 'Mega Altaria'),
    (54, 'Lombre', 'Mega Altaria'),
    (55, 'Ludicolo', 'Mega Altaria'),
    (56, 'Wailmer', 'Mega Gyarados'),
    (57, 'Wailord', 'Mega Gyarados'),
    (58, 'Corphish', 'Shared'),
    (59, 'Crawdaunt', 'Shared'),
    (60, 'Luvdisc', 'Mega Altaria'),
    (61, 'Panpour', 'Mega Altaria'),
    (62, 'Simipour', 'Mega Altaria'),
    (63, 'Tympole', 'Shared'),
    (64, 'Palpitoad', 'Shared'),
    (65, 'Seismitoad', 'Shared'),
    (66, 'Tirtouga', 'Mega Gyarados'),
    (67, 'Carracosta', 'Mega Gyarados'),
    (68, 'Frillish', 'Mega Gyarados'),
    (69, 'Jellicent', 'Mega Gyarados'),
    (70, 'Keldeo', 'Mega Blaziken'),
    (71, 'Froakie', 'Mega Gyarados'),
    (72, 'Frogadier', 'Mega Gyarados'),
    (73, 'Greninja ex', 'Mega Gyarados'),
    (74, 'Bergmite', 'Mega Gyarados'),
    (75, 'Avalugg', 'Mega Gyarados'),
    (76, 'Chewtle', 'Mega Gyarados'),
    (77, 'Drednaw', 'Mega Gyarados'),
    (78, 'Arrokuda', 'Mega Gyarados'),
    (79, 'Barraskewda', 'Mega Gyarados'),
    (80, 'Eiscue', 'Mega Altaria'),
    (81, 'Jolteon ex', 'Mega Gyarados'),
    (82, 'Mareep', 'Mega Altaria'),
    (83, 'Flaaffy', 'Mega Altaria'),
    (84, 'Ampharos', 'Mega Altaria'),
    (85, 'Mega Ampharos ex', 'Mega Altaria'),
    (86, 'Shinx', 'Mega Blaziken'),
    (87, 'Luxio', 'Mega Blaziken'),
    (88, 'Luxray', 'Mega Blaziken'),
    (89, 'Pachirisu', 'Shared'),
    (90, 'Blitzle', 'Mega Blaziken'),
    (91, 'Zebstrika', 'Mega Blaziken'),
    (92, 'Joltik', 'Shared'),
    (93, 'Galvantula', 'Shared'),
    (94, 'Dedenne', 'Mega Altaria'),
    (95, 'Yamper', 'Mega Altaria'),
    (96, 'Boltund', 'Mega Altaria'),
    (97, 'Natu', 'Shared'),
    (98, 'Xatu', 'Shared'),
    (99, 'Misdreavus', 'Shared'),
    (100, 'Mismagius', 'Shared'),
    (101, 'Sableye', 'Mega Altaria'),
    (102, 'Mega Altaria ex', 'Mega Altaria'),
    (103, 'Duskull', 'Mega Blaziken'),
    (104, 'Dusclops', 'Mega Blaziken'),
    (105, 'Dusknoir', 'Mega Blaziken'),
    (106, 'Jirachi', 'Mega Altaria'),
    (107, 'Drifloon', 'Mega Altaria'),
    (108, 'Drifblim', 'Mega Altaria'),
    (109, 'Chingling', 'Shared'),
    (110, 'Yamask', 'Mega Gyarados'),
    (111, 'Cofagrigus', 'Mega Gyarados'),
    (112, 'Gothita', 'Mega Altaria'),
    (113, 'Gothorita', 'Mega Altaria'),
    (114, 'Gothitelle', 'Mega Altaria'),
    (115, 'Spritzee', 'Shared'),
    (116, 'Aromatisse', 'Shared'),
    (117, 'Swirlix', 'Mega Altaria'),
    (118, 'Slurpuff', 'Mega Altaria'),
    (119, 'Carbink', 'Mega Altaria'),
    (120, 'Klefki', 'Mega Gyarados'),
    (121, 'Indeedee ex', 'Mega Altaria'),
    (122, 'Sandshrew', 'Shared'),
    (123, 'Sandslash', 'Shared'),
    (124, 'Hitmonchan ex', 'Mega Blaziken'),
    (125, 'Sudowoodo', 'Shared'),
    (126, 'Makuhita', 'Mega Blaziken'),
    (127, 'Hariyama', 'Mega Blaziken'),
    (128, 'Hippopotas', 'Mega Gyarados'),
    (129, 'Hippowdon', 'Mega Gyarados'),
    (130, 'Sandile', 'Mega Gyarados'),
    (131, 'Krokorok', 'Mega Gyarados'),
    (132, 'Krookodile', 'Mega Gyarados'),
    (133, 'Archen', 'Mega Blaziken'),
    (134, 'Archeops', 'Mega Blaziken'),
    (135, 'Golett', 'Mega Blaziken'),
    (136, 'Golurk', 'Mega Blaziken'),
    (137, 'Terrakion', 'Mega Gyarados'),
    (138, 'Pancham', 'Mega Gyarados'),
    (139, 'Crabrawler', 'Mega Blaziken'),
    (140, 'Crabominable', 'Mega Blaziken'),
    (141, 'Stufful', 'Mega Blaziken'),
    (142, 'Bewear', 'Mega Blaziken'),
    (143, 'Sandygast', 'Shared'),
    (144, 'Palossand', 'Shared'),
    (145, 'Rolycoly', 'Mega Gyarados'),
    (146, 'Carkol', 'Mega Gyarados'),
    (147, 'Coalossal', 'Mega Gyarados'),
    (148, 'Murkrow', 'Mega Gyarados'),
    (149, 'Honchkrow', 'Mega Gyarados'),
    (150, 'Absol', 'Mega Gyarados'),
    (151, 'Mega Absol ex', 'Mega Gyarados'),
    (152, 'Skorupi', 'Mega Gyarados'),
    (153, 'Drapion', 'Mega Gyarados'),
    (154, 'Darkrai', 'Mega Altaria'),
    (155, 'Deino', 'Mega Gyarados'),
    (156, 'Zweilous', 'Mega Gyarados'),
    (157, 'Hydreigon', 'Mega Gyarados'),
    (158, 'Pangoro', 'Mega Gyarados'),
    (159, 'Skrelp', 'Mega Blaziken'),
    (160, 'Dragalge ex', 'Mega Blaziken'),
    (161, 'Mareanie', 'Shared'),
    (162, 'Toxapex', 'Shared'),
    (163, 'Impidimp', 'Mega Altaria'),
    (164, 'Morgrem', 'Mega Altaria'),
    (165, 'Grimmsnarl', 'Mega Altaria'),
    (166, 'Ferroseed', 'Shared'),
    (167, 'Ferrothorn', 'Shared'),
    (168, 'Durant', 'Shared'),
    (169, 'Cobalion', 'Mega Blaziken'),
    (170, 'Honedge', 'Mega Blaziken'),
    (171, 'Doublade', 'Mega Blaziken'),
    (172, 'Aegislash', 'Mega Blaziken'),
    (173, 'Meltan', 'Mega Gyarados'),
    (174, 'Melmetal ex', 'Mega Gyarados'),
    (175, 'Corviknight', 'Mega Blaziken'),
    (176, 'Druddigon', 'Mega Gyarados'),
    (177, 'Goomy', 'Mega Altaria'),
    (178, 'Sliggoo', 'Mega Altaria'),
    (179, 'Goodra', 'Mega Altaria'),
    (180, 'Pidgey', 'Shared'),
    (181, 'Pidgeotto', 'Shared'),
    (182, 'Pidgeot', 'Shared'),
    (183, 'Tauros ex', 'Mega Altaria'),
    (184, 'Eevee', 'Mega Gyarados'),
    (185, 'Aipom', 'Mega Altaria'),
    (186, 'Ambipom', 'Mega Altaria'),
    (187, 'Miltank', 'Shared'),
    (188, 'Zigzagoon', 'Shared'),
    (189, 'Linoone', 'Shared'),
    (190, 'Whismur', 'Mega Gyarados'),
    (191, 'Loudred', 'Mega Gyarados'),
    (192, 'Exploud', 'Mega Gyarados'),
    (193, 'Skitty', 'Mega Gyarados'),
    (194, 'Delcatty', 'Mega Gyarados'),
    (195, 'Spinda', 'Mega Altaria'),
    (196, 'Swablu', 'Mega Altaria'),
    (197, 'Altaria', 'Mega Altaria'),
    (198, 'Chatot', 'Shared'),
    (199, 'Patrat', 'Shared'),
    (200, 'Watchog', 'Shared'),
    (201, 'Lillipup', 'Mega Altaria'),
    (202, 'Herdier', 'Mega Altaria'),
    (203, 'Stoutland', 'Mega Altaria'),
    (204, 'Rufflet', 'Mega Blaziken'),
    (205, 'Braviary', 'Mega Blaziken'),
    (206, 'Furfrou', 'Mega Blaziken'),
    (207, 'Furfrou', 'Mega Altaria'),
    (208, 'Furfrou', 'Mega Gyarados'),
    (209, 'Rookidee', 'Mega Blaziken'),
    (210, 'Corvisquire', 'Mega Blaziken'),
    (211, 'Wooloo', 'Mega Altaria'),
    (212, 'Dubwool', 'Mega Altaria'),
    (213, 'Prank Spinner', 'Mega Blaziken'),
    (214, 'Plume Fossil', 'Mega Blaziken'),
    (215, 'Hitting Hammer', 'Mega Gyarados'),
    (216, 'Cover Fossil', 'Mega Gyarados'),
    (217, 'Flame Patch', 'Mega Blaziken'),
    (218, 'Sitrus Berry', 'Mega Altaria'),
    (219, 'Heavy Helmet', 'Mega Gyarados'),
    (220, 'Lucky Mittens', 'Mega Altaria'),
    (221, 'Marlon', 'Mega Gyarados'),
    (222, 'Hala', 'Mega Blaziken'),
    (223, 'May', 'Mega Blaziken'),
    (224, 'Fantina', 'Mega Altaria'),
    (225, 'Copycat', 'Mega Gyarados'),
    (226, 'Lisia', 'Mega Altaria'),
    (227, 'Beautifly', 'Mega Blaziken'),
    (228, 'Skiddo', 'Mega Altaria'),
    (229, 'Rillaboom', 'Mega Altaria'),
    (230, 'Growlithe', 'Mega Blaziken'),
    (231, 'Chandelure', 'Mega Altaria'),
    (232, 'Magikarp', 'Mega Gyarados'),
    (233, 'Ludicolo', 'Mega Altaria'),
    (234, 'Jellicent', 'Mega Gyarados'),
    (235, 'Keldeo', 'Mega Blaziken'),
    (236, 'Eiscue', 'Mega Altaria'),
    (237, 'Luxray', 'Mega Blaziken'),
    (238, 'Cofagrigus', 'Mega Gyarados'),
    (239, 'Gothita', 'Mega Altaria'),
    (240, 'Makuhita', 'Mega Blaziken'),
    (241, 'Hippowdon', 'Mega Gyarados'),
    (242, 'Archeops', 'Mega Blaziken'),
    (243, 'Pancham', 'Mega Gyarados'),
    (244, 'Honchkrow', 'Mega Gyarados'),
    (245, 'Hydreigon', 'Mega Gyarados'),
    (246, 'Corviknight', 'Mega Blaziken'),
    (247, 'Goomy', 'Mega Altaria'),
    (248, 'Delcatty', 'Mega Gyarados'),
    (249, 'Stoutland', 'Mega Altaria'),
    (250, 'Rufflet', 'Mega Blaziken'),
    (251, 'Mega Pinsir ex', 'Mega Blaziken'),
    (252, 'Whimsicott ex', 'Mega Altaria'),
    (253, 'Rapidash ex', 'Mega Blaziken'),
    (254, 'Mega Blaziken ex', 'Mega Blaziken'),
    (255, 'Mega Gyarados ex', 'Mega Gyarados'),
    (256, 'Greninja ex', 'Mega Gyarados'),
    (257, 'Jolteon ex', 'Mega Gyarados'),
    (258, 'Mega Ampharos ex', 'Mega Altaria'),
    (259, 'Mega Altaria ex', 'Mega Altaria'),
    (260, 'Indeedee ex', 'Mega Altaria'),
    (261, 'Hitmonchan ex', 'Mega Blaziken'),
    (262, 'Mega Absol ex', 'Mega Gyarados'),
    (263, 'Dragalge ex', 'Mega Blaziken'),
    (264, 'Melmetal ex', 'Mega Gyarados'),
    (265, 'Tauros ex', 'Mega Altaria'),
    (266, 'Marlon', 'Mega Gyarados'),
    (267, 'Hala', 'Mega Blaziken'),
    (268, 'May', 'Mega Blaziken'),
    (269, 'Fantina', 'Mega Altaria'),
    (270, 'Copycat', 'Mega Gyarados'),
    (271, 'Lisia', 'Mega Altaria'),
    (272, 'Mega Pinsir ex', 'Mega Blaziken'),
    (273, 'Whimsicott ex', 'Mega Altaria'),
    (274, 'Rapidash ex', 'Mega Blaziken'),
    (275, 'Greninja ex', 'Mega Gyarados'),
    (276, 'Jolteon ex', 'Mega Gyarados'),
    (277, 'Mega Ampharos ex', 'Mega Altaria'),
    (278, 'Indeedee ex', 'Mega Altaria'),
    (279, 'Hitmonchan ex', 'Mega Blaziken'),
    (280, 'Mega Absol ex', 'Mega Gyarados'),
    (281, 'Dragalge ex', 'Mega Blaziken'),
    (282, 'Melmetal ex', 'Mega Gyarados'),
    (283, 'Tauros ex', 'Mega Altaria'),
    (284, 'Mega Blaziken ex', 'Mega Blaziken'),
    (285, 'Mega Gyarados ex', 'Mega Gyarados'),
    (286, 'Mega Altaria ex', 'Mega Altaria'),
    (287, 'Bellsprout', 'Mega Altaria'),
    (288, 'Weepinbell', 'Mega Altaria'),
    (289, 'Victreebel', 'Mega Altaria'),
    (290, 'Rowlet', 'Mega Blaziken'),
    (291, 'Dartrix', 'Mega Blaziken'),
    (292, 'Moltres', 'Mega Blaziken'),
    (293, 'Litten', 'Mega Gyarados'),
    (294, 'Torracat', 'Mega Gyarados'),
    (295, 'Poliwag', 'Mega Gyarados'),
    (296, 'Poliwhirl', 'Mega Gyarados'),
    (297, 'Poliwrath', 'Mega Gyarados'),
    (298, 'Articuno', 'Mega Altaria'),
    (299, 'Manaphy', 'Mega Blaziken'),
    (300, 'Popplio', 'Mega Altaria'),
    (301, 'Brionne', 'Mega Altaria'),
    (302, 'Zapdos', 'Mega Gyarados'),
    (303, 'Oricorio', 'Mega Gyarados'),
    (304, 'Zeraora', 'Mega Altaria'),
    (305, 'Drowzee', 'Mega Gyarados'),
    (306, 'Hypno', 'Mega Gyarados'),
    (307, 'Geodude', 'Mega Blaziken'),
    (308, 'Graveler', 'Mega Blaziken'),
    (309, 'Golem', 'Mega Blaziken'),
    (310, 'Rockruff', 'Mega Gyarados'),
    (311, 'Alolan Diglett', 'Mega Blaziken'),
    (312, 'Meowth', 'Mega Altaria'),
    (313, 'Persian', 'Mega Altaria'),
    (314, 'Doduo', 'Mega Blaziken'),
    (315, 'Dodrio', 'Mega Blaziken'),
    (316, 'Bidoof', 'Mega Altaria'),
    (317, 'Decidueye ex', 'Mega Blaziken'),
    (318, 'Incineroar ex', 'Mega Gyarados'),
    (319, 'Palkia ex', 'Mega Blaziken'),
    (320, 'Primarina ex', 'Mega Altaria'),
    (321, 'Pikachu ex', 'Mega Gyarados'),
    (322, 'Tapu Koko ex', 'Mega Blaziken'),
    (323, 'Lycanroc ex', 'Mega Gyarados'),
    (324, 'Passimian ex', 'Mega Altaria'),
    (325, 'Alolan Dugtrio ex', 'Mega Blaziken'),
    (326, 'Dialga ex', 'Mega Altaria'),
    (327, 'Bibarel ex', 'Mega Altaria'),
    (328, 'Arceus ex', 'Mega Gyarados'),
    (329, 'Lilligant', 'Shared'),
    (330, 'Klefki', 'Shared'),
    (331, 'Flame Patch', 'Shared')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
