-- Crimson Blaze (B1a) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B1a
-- Limitless lists Crimson Blaze as B1a with 103 cards.
-- Crimson Blaze has one booster pack, represented here as Crimson Blaze.

insert into public.cards (id, name, pack, image)
select
  'B1a-' || lpad(card_number::text, 3, '0') as id,
  name,
  'Crimson Blaze' as pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B1a/B1a_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Bulbasaur'),
    (2, 'Ivysaur'),
    (3, 'Venusaur'),
    (4, 'Mega Venusaur ex'),
    (5, 'Spinarak'),
    (6, 'Ariados'),
    (7, 'Sunkern'),
    (8, 'Sunflora'),
    (9, 'Burmy'),
    (10, 'Mothim'),
    (11, 'Charmander'),
    (12, 'Charmeleon'),
    (13, 'Charizard'),
    (14, 'Mega Charizard Y ex'),
    (15, 'Houndour'),
    (16, 'Houndoom'),
    (17, 'Squirtle'),
    (18, 'Wartortle'),
    (19, 'Blastoise'),
    (20, 'Mega Blastoise ex'),
    (21, 'Basculin'),
    (22, 'Clauncher'),
    (23, 'Clawitzer'),
    (24, 'Magnemite'),
    (25, 'Magneton'),
    (26, 'Magnezone'),
    (27, 'Emolga'),
    (28, 'Helioptile'),
    (29, 'Heliolisk'),
    (30, 'Misdreavus'),
    (31, 'Mismagius'),
    (32, 'Solosis'),
    (33, 'Duosion'),
    (34, 'Reuniclus'),
    (35, 'Spritzee'),
    (36, 'Aromatisse'),
    (37, 'Xerneas'),
    (38, 'Onix'),
    (39, 'Makuhita'),
    (40, 'Hariyama'),
    (41, 'Nosepass'),
    (42, 'Mega Lopunny ex'),
    (43, 'Mienfoo'),
    (44, 'Mienshao'),
    (45, 'Grimer'),
    (46, 'Muk'),
    (47, 'Purrloin'),
    (48, 'Liepard'),
    (49, 'Trubbish'),
    (50, 'Garbodor'),
    (51, 'Steelix'),
    (52, 'Mega Steelix ex'),
    (53, 'Probopass'),
    (54, 'Genesect'),
    (55, 'Ditto'),
    (56, 'Porygon'),
    (57, 'Porygon2'),
    (58, 'Porygon-Z'),
    (59, 'Starly'),
    (60, 'Staravia'),
    (61, 'Staraptor'),
    (62, 'Buneary'),
    (63, 'Lopunny'),
    (64, 'Bouffalant'),
    (65, 'Furfrou'),
    (66, 'Clemont''s Backpack'),
    (67, 'Quick-Grow Extract'),
    (68, 'Clemont'),
    (69, 'Serena'),
    (70, 'Ariados'),
    (71, 'Sunflora'),
    (72, 'Reuniclus'),
    (73, 'Xerneas'),
    (74, 'Trubbish'),
    (75, 'Buneary'),
    (76, 'Mega Venusaur ex'),
    (77, 'Mega Charizard Y ex'),
    (78, 'Mega Blastoise ex'),
    (79, 'Mega Lopunny ex'),
    (80, 'Mega Steelix ex'),
    (81, 'Clemont'),
    (82, 'Serena'),
    (83, 'Mega Venusaur ex'),
    (84, 'Mega Blastoise ex'),
    (85, 'Mega Lopunny ex'),
    (86, 'Mega Steelix ex'),
    (87, 'Mega Charizard Y ex'),
    (88, 'Oddish'),
    (89, 'Gloom'),
    (90, 'Vileplume'),
    (91, 'Charizard'),
    (92, 'Shellder'),
    (93, 'Cloyster'),
    (94, 'Sandshrew'),
    (95, 'Sandslash'),
    (96, 'Type: Null'),
    (97, 'Silvally'),
    (98, 'Buzzwole ex'),
    (99, 'Lunala ex'),
    (100, 'Guzzlord ex'),
    (101, 'Solgaleo ex'),
    (102, 'Aegislash'),
    (103, 'Quick-Grow Extract')
) as card_seed(card_number, name)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
