-- Fantastical Parade (B2) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B2
-- Limitless lists Fantastical Parade as B2 with 234 cards.
-- Fantastical Parade has one booster pack, represented here as Fantastical Parade.

insert into public.cards (id, name, pack, image)
select
  'B2-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2/B2_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Ledyba', 'Fantastical Parade'),
    (2, 'Ledian', 'Fantastical Parade'),
    (3, 'Shuckle', 'Fantastical Parade'),
    (4, 'Roselia', 'Fantastical Parade'),
    (5, 'Roserade', 'Fantastical Parade'),
    (6, 'Cacnea', 'Fantastical Parade'),
    (7, 'Cacturne', 'Fantastical Parade'),
    (8, 'Chespin', 'Fantastical Parade'),
    (9, 'Quilladin', 'Fantastical Parade'),
    (10, 'Chesnaught', 'Fantastical Parade'),
    (11, 'Scatterbug', 'Fantastical Parade'),
    (12, 'Spewpa', 'Fantastical Parade'),
    (13, 'Vivillon', 'Fantastical Parade'),
    (14, 'Buzzwole', 'Fantastical Parade'),
    (15, 'Gossifleur', 'Fantastical Parade'),
    (16, 'Eldegoss', 'Fantastical Parade'),
    (17, 'Teal Mask Ogerpon ex', 'Fantastical Parade'),
    (18, 'Alolan Marowak', 'Fantastical Parade'),
    (19, 'Reshiram', 'Fantastical Parade'),
    (20, 'Litleo', 'Fantastical Parade'),
    (21, 'Pyroar', 'Fantastical Parade'),
    (22, 'Oricorio', 'Fantastical Parade'),
    (23, 'Blacephalon ex', 'Fantastical Parade'),
    (24, 'Scorbunny', 'Fantastical Parade'),
    (25, 'Raboot', 'Fantastical Parade'),
    (26, 'Cinderace', 'Fantastical Parade'),
    (27, 'Hearthflame Mask Ogerpon', 'Fantastical Parade'),
    (28, 'Alolan Vulpix', 'Fantastical Parade'),
    (29, 'Alolan Ninetales ex', 'Fantastical Parade'),
    (30, 'Galarian Mr. Mime', 'Fantastical Parade'),
    (31, 'Galarian Mr. Rime', 'Fantastical Parade'),
    (32, 'Delibird', 'Fantastical Parade'),
    (33, 'Mudkip', 'Fantastical Parade'),
    (34, 'Marshtomp', 'Fantastical Parade'),
    (35, 'Swampert', 'Fantastical Parade'),
    (36, 'Mega Swampert ex', 'Fantastical Parade'),
    (37, 'Vanillite', 'Fantastical Parade'),
    (38, 'Vanillish', 'Fantastical Parade'),
    (39, 'Vanilluxe', 'Fantastical Parade'),
    (40, 'Cryogonal', 'Fantastical Parade'),
    (41, 'Amaura', 'Fantastical Parade'),
    (42, 'Aurorus', 'Fantastical Parade'),
    (43, 'Chewtle', 'Fantastical Parade'),
    (44, 'Drednaw', 'Fantastical Parade'),
    (45, 'Cramorant', 'Fantastical Parade'),
    (46, 'Arrokuda', 'Fantastical Parade'),
    (47, 'Barraskewda', 'Fantastical Parade'),
    (48, 'Wellspring Mask Ogerpon', 'Fantastical Parade'),
    (49, 'Pikachu', 'Fantastical Parade'),
    (50, 'Alolan Raichu', 'Fantastical Parade'),
    (51, 'Zapdos', 'Fantastical Parade'),
    (52, 'Plusle', 'Fantastical Parade'),
    (53, 'Minun', 'Fantastical Parade'),
    (54, 'Toxel', 'Fantastical Parade'),
    (55, 'Toxtricity ex', 'Fantastical Parade'),
    (56, 'Tadbulb', 'Fantastical Parade'),
    (57, 'Bellibolt', 'Fantastical Parade'),
    (58, 'Galarian Ponyta', 'Fantastical Parade'),
    (59, 'Galarian Rapidash', 'Fantastical Parade'),
    (60, 'Wobbuffet', 'Fantastical Parade'),
    (61, 'Snubbull', 'Fantastical Parade'),
    (62, 'Granbull', 'Fantastical Parade'),
    (63, 'Ralts', 'Fantastical Parade'),
    (64, 'Kirlia', 'Fantastical Parade'),
    (65, 'Gardevoir', 'Fantastical Parade'),
    (66, 'Mega Gardevoir ex', 'Fantastical Parade'),
    (67, 'Litwick', 'Fantastical Parade'),
    (68, 'Lampent', 'Fantastical Parade'),
    (69, 'Chandelure', 'Fantastical Parade'),
    (70, 'Meloetta', 'Fantastical Parade'),
    (71, 'Pumpkaboo', 'Fantastical Parade'),
    (72, 'Gourgeist', 'Fantastical Parade'),
    (73, 'Mimikyu ex', 'Fantastical Parade'),
    (74, 'Sinistea', 'Fantastical Parade'),
    (75, 'Polteageist', 'Fantastical Parade'),
    (76, 'Indeedee', 'Fantastical Parade'),
    (77, 'Sandshrew', 'Fantastical Parade'),
    (78, 'Sandslash', 'Fantastical Parade'),
    (79, 'Machop', 'Fantastical Parade'),
    (80, 'Machoke', 'Fantastical Parade'),
    (81, 'Machamp', 'Fantastical Parade'),
    (82, 'Cubone', 'Fantastical Parade'),
    (83, 'Meditite', 'Fantastical Parade'),
    (84, 'Medicham', 'Fantastical Parade'),
    (85, 'Roggenrola', 'Fantastical Parade'),
    (86, 'Boldore', 'Fantastical Parade'),
    (87, 'Gigalith ex', 'Fantastical Parade'),
    (88, 'Drilbur', 'Fantastical Parade'),
    (89, 'Tyrunt', 'Fantastical Parade'),
    (90, 'Tyrantrum', 'Fantastical Parade'),
    (91, 'Passimian', 'Fantastical Parade'),
    (92, 'Falinks', 'Fantastical Parade'),
    (93, 'Cornerstone Mask Ogerpon', 'Fantastical Parade'),
    (94, 'Alolan Meowth', 'Fantastical Parade'),
    (95, 'Alolan Persian', 'Fantastical Parade'),
    (96, 'Alolan Grimer', 'Fantastical Parade'),
    (97, 'Alolan Muk', 'Fantastical Parade'),
    (98, 'Galarian Zigzagoon', 'Fantastical Parade'),
    (99, 'Galarian Linoone', 'Fantastical Parade'),
    (100, 'Galarian Obstagoon', 'Fantastical Parade'),
    (101, 'Stunky', 'Fantastical Parade'),
    (102, 'Skuntank', 'Fantastical Parade'),
    (103, 'Spiritomb', 'Fantastical Parade'),
    (104, 'Purrloin', 'Fantastical Parade'),
    (105, 'Liepard', 'Fantastical Parade'),
    (106, 'Scraggy', 'Fantastical Parade'),
    (107, 'Scrafty', 'Fantastical Parade'),
    (108, 'Yveltal', 'Fantastical Parade'),
    (109, 'Guzzlord', 'Fantastical Parade'),
    (110, 'Galarian Meowth', 'Fantastical Parade'),
    (111, 'Galarian Perrserker', 'Fantastical Parade'),
    (112, 'Mawile', 'Fantastical Parade'),
    (113, 'Mega Mawile ex', 'Fantastical Parade'),
    (114, 'Excadrill', 'Fantastical Parade'),
    (115, 'Ferroseed', 'Fantastical Parade'),
    (116, 'Ferrothorn', 'Fantastical Parade'),
    (117, 'Galarian Stunfisk', 'Fantastical Parade'),
    (118, 'Honedge', 'Fantastical Parade'),
    (119, 'Doublade', 'Fantastical Parade'),
    (120, 'Aegislash', 'Fantastical Parade'),
    (121, 'Bagon', 'Fantastical Parade'),
    (122, 'Shelgon', 'Fantastical Parade'),
    (123, 'Salamence', 'Fantastical Parade'),
    (124, 'Meowth', 'Fantastical Parade'),
    (125, 'Persian', 'Fantastical Parade'),
    (126, 'Kangaskhan', 'Fantastical Parade'),
    (127, 'Mega Kangaskhan ex', 'Fantastical Parade'),
    (128, 'Sentret', 'Fantastical Parade'),
    (129, 'Furret', 'Fantastical Parade'),
    (130, 'Smeargle', 'Fantastical Parade'),
    (131, 'Lugia', 'Fantastical Parade'),
    (132, 'Taillow', 'Fantastical Parade'),
    (133, 'Swellow', 'Fantastical Parade'),
    (134, 'Slakoth', 'Fantastical Parade'),
    (135, 'Vigoroth', 'Fantastical Parade'),
    (136, 'Slaking', 'Fantastical Parade'),
    (137, 'Spinda', 'Fantastical Parade'),
    (138, 'Tornadus', 'Fantastical Parade'),
    (139, 'Bunnelby', 'Fantastical Parade'),
    (140, 'Diggersby', 'Fantastical Parade'),
    (141, 'Furfrou', 'Fantastical Parade'),
    (142, 'Tandemaus', 'Fantastical Parade'),
    (143, 'Maushold', 'Fantastical Parade'),
    (144, 'Jaw Fossil', 'Fantastical Parade'),
    (145, 'Lucky Ice Pop', 'Fantastical Parade'),
    (146, 'Sail Fossil', 'Fantastical Parade'),
    (147, 'Protective Poncho', 'Fantastical Parade'),
    (148, 'Metal Core Barrier', 'Fantastical Parade'),
    (149, 'Diantha', 'Fantastical Parade'),
    (150, 'Sightseer', 'Fantastical Parade'),
    (151, 'Juggler', 'Fantastical Parade'),
    (152, 'Piers', 'Fantastical Parade'),
    (153, 'Training Area', 'Fantastical Parade'),
    (154, 'Starting Plains', 'Fantastical Parade'),
    (155, 'Peculiar Plaza', 'Fantastical Parade'),
    (156, 'Cacnea', 'Fantastical Parade'),
    (157, 'Roserade', 'Fantastical Parade'),
    (158, 'Vivillon', 'Fantastical Parade'),
    (159, 'Buzzwole', 'Fantastical Parade'),
    (160, 'Reshiram', 'Fantastical Parade'),
    (161, 'Oricorio', 'Fantastical Parade'),
    (162, 'Scorbunny', 'Fantastical Parade'),
    (163, 'Aurorus', 'Fantastical Parade'),
    (164, 'Cramorant', 'Fantastical Parade'),
    (165, 'Minun', 'Fantastical Parade'),
    (166, 'Toxel', 'Fantastical Parade'),
    (167, 'Galarian Ponyta', 'Fantastical Parade'),
    (168, 'Snubbull', 'Fantastical Parade'),
    (169, 'Indeedee', 'Fantastical Parade'),
    (170, 'Sandshrew', 'Fantastical Parade'),
    (171, 'Tyrantrum', 'Fantastical Parade'),
    (172, 'Falinks', 'Fantastical Parade'),
    (173, 'Alolan Muk', 'Fantastical Parade'),
    (174, 'Purrloin', 'Fantastical Parade'),
    (175, 'Yveltal', 'Fantastical Parade'),
    (176, 'Galarian Obstagoon', 'Fantastical Parade'),
    (177, 'Galarian Perrserker', 'Fantastical Parade'),
    (178, 'Salamence', 'Fantastical Parade'),
    (179, 'Slakoth', 'Fantastical Parade'),
    (180, 'Teal Mask Ogerpon ex', 'Fantastical Parade'),
    (181, 'Blacephalon ex', 'Fantastical Parade'),
    (182, 'Alolan Ninetales ex', 'Fantastical Parade'),
    (183, 'Mega Swampert ex', 'Fantastical Parade'),
    (184, 'Toxtricity ex', 'Fantastical Parade'),
    (185, 'Mega Gardevoir ex', 'Fantastical Parade'),
    (186, 'Mimikyu ex', 'Fantastical Parade'),
    (187, 'Gigalith ex', 'Fantastical Parade'),
    (188, 'Mega Mawile ex', 'Fantastical Parade'),
    (189, 'Mega Kangaskhan ex', 'Fantastical Parade'),
    (190, 'Diantha', 'Fantastical Parade'),
    (191, 'Sightseer', 'Fantastical Parade'),
    (192, 'Juggler', 'Fantastical Parade'),
    (193, 'Piers', 'Fantastical Parade'),
    (194, 'Teal Mask Ogerpon ex', 'Fantastical Parade'),
    (195, 'Blacephalon ex', 'Fantastical Parade'),
    (196, 'Alolan Ninetales ex', 'Fantastical Parade'),
    (197, 'Mega Swampert ex', 'Fantastical Parade'),
    (198, 'Toxtricity ex', 'Fantastical Parade'),
    (199, 'Mimikyu ex', 'Fantastical Parade'),
    (200, 'Gigalith ex', 'Fantastical Parade'),
    (201, 'Mega Mawile ex', 'Fantastical Parade'),
    (202, 'Mega Kangaskhan ex', 'Fantastical Parade'),
    (203, 'Mega Gardevoir ex', 'Fantastical Parade'),
    (204, 'Meowth', 'Fantastical Parade'),
    (205, 'Tangela', 'Fantastical Parade'),
    (206, 'Magby', 'Fantastical Parade'),
    (207, 'Magmar', 'Fantastical Parade'),
    (208, 'Horsea', 'Fantastical Parade'),
    (209, 'Seadra', 'Fantastical Parade'),
    (210, 'Mantyke', 'Fantastical Parade'),
    (211, 'Omanyte', 'Fantastical Parade'),
    (212, 'Omastar', 'Fantastical Parade'),
    (213, 'Pichu', 'Fantastical Parade'),
    (214, 'Clefairy', 'Fantastical Parade'),
    (215, 'Clefable', 'Fantastical Parade'),
    (216, 'Latias', 'Fantastical Parade'),
    (217, 'Latios', 'Fantastical Parade'),
    (218, 'Hitmonlee', 'Fantastical Parade'),
    (219, 'Hitmonchan', 'Fantastical Parade'),
    (220, 'Kabuto', 'Fantastical Parade'),
    (221, 'Kabutops', 'Fantastical Parade'),
    (222, 'Phanpy', 'Fantastical Parade'),
    (223, 'Tyrogue', 'Fantastical Parade'),
    (224, 'Tauros', 'Fantastical Parade'),
    (225, 'Flareon ex', 'Fantastical Parade'),
    (226, 'Ho-Oh ex', 'Fantastical Parade'),
    (227, 'Kingdra ex', 'Fantastical Parade'),
    (228, 'Espeon ex', 'Fantastical Parade'),
    (229, 'Sylveon ex', 'Fantastical Parade'),
    (230, 'Donphan ex', 'Fantastical Parade'),
    (231, 'Umbreon ex', 'Fantastical Parade'),
    (232, 'Lugia ex', 'Fantastical Parade'),
    (233, 'Meloetta', 'Fantastical Parade'),
    (234, 'Protective Poncho', 'Fantastical Parade')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
