-- Pulsing Aura (B3) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B3
-- Limitless lists Pulsing Aura as B3 with 234 cards.
-- Pulsing Aura has one booster pack, represented here as Pulsing Aura.

insert into public.cards (id, name, pack, image)
select
  'B3-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3/B3_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Tangela', 'Pulsing Aura'),
    (2, 'Tangrowth', 'Pulsing Aura'),
    (3, 'Heracross', 'Pulsing Aura'),
    (4, 'Celebi', 'Pulsing Aura'),
    (5, 'Treecko', 'Pulsing Aura'),
    (6, 'Grovyle', 'Pulsing Aura'),
    (7, 'Sceptile', 'Pulsing Aura'),
    (8, 'Mega Sceptile ex', 'Pulsing Aura'),
    (9, 'Surskit', 'Pulsing Aura'),
    (10, 'Masquerain', 'Pulsing Aura'),
    (11, 'Shroomish', 'Pulsing Aura'),
    (12, 'Breloom', 'Pulsing Aura'),
    (13, 'Budew', 'Pulsing Aura'),
    (14, 'Carnivine', 'Pulsing Aura'),
    (15, 'Sewaddle', 'Pulsing Aura'),
    (16, 'Swadloon', 'Pulsing Aura'),
    (17, 'Leavanny', 'Pulsing Aura'),
    (18, 'Durant', 'Pulsing Aura'),
    (19, 'Applin', 'Pulsing Aura'),
    (20, 'Flapple', 'Pulsing Aura'),
    (21, 'Numel', 'Pulsing Aura'),
    (22, 'Camerupt', 'Pulsing Aura'),
    (23, 'Mega Camerupt ex', 'Pulsing Aura'),
    (24, 'Castform Sunny Form', 'Pulsing Aura'),
    (25, 'Victini', 'Pulsing Aura'),
    (26, 'Tepig', 'Pulsing Aura'),
    (27, 'Pignite', 'Pulsing Aura'),
    (28, 'Emboar', 'Pulsing Aura'),
    (29, 'Darumaka', 'Pulsing Aura'),
    (30, 'Darmanitan', 'Pulsing Aura'),
    (31, 'Larvesta', 'Pulsing Aura'),
    (32, 'Volcarona', 'Pulsing Aura'),
    (33, 'Poliwag', 'Pulsing Aura'),
    (34, 'Poliwhirl', 'Pulsing Aura'),
    (35, 'Politoed', 'Pulsing Aura'),
    (36, 'Paldean Tauros', 'Pulsing Aura'),
    (37, 'Vaporeon ex', 'Pulsing Aura'),
    (38, 'Wooper', 'Pulsing Aura'),
    (39, 'Quagsire', 'Pulsing Aura'),
    (40, 'Castform Rainy Form', 'Pulsing Aura'),
    (41, 'Castform Snowy Form', 'Pulsing Aura'),
    (42, 'Clamperl', 'Pulsing Aura'),
    (43, 'Huntail', 'Pulsing Aura'),
    (44, 'Gorebyss', 'Pulsing Aura'),
    (45, 'Regice', 'Pulsing Aura'),
    (46, 'Cubchoo', 'Pulsing Aura'),
    (47, 'Beartic', 'Pulsing Aura'),
    (48, 'Sobble', 'Pulsing Aura'),
    (49, 'Drizzile', 'Pulsing Aura'),
    (50, 'Inteleon', 'Pulsing Aura'),
    (51, 'Rapid Strike Urshifu', 'Pulsing Aura'),
    (52, 'Magnemite', 'Pulsing Aura'),
    (53, 'Magneton', 'Pulsing Aura'),
    (54, 'Magnezone ex', 'Pulsing Aura'),
    (55, 'Voltorb', 'Pulsing Aura'),
    (56, 'Electrode', 'Pulsing Aura'),
    (57, 'Chinchou', 'Pulsing Aura'),
    (58, 'Lanturn', 'Pulsing Aura'),
    (59, 'Zekrom', 'Pulsing Aura'),
    (60, 'Toxel', 'Pulsing Aura'),
    (61, 'Toxtricity', 'Pulsing Aura'),
    (62, 'Morpeko', 'Pulsing Aura'),
    (63, 'Ralts', 'Pulsing Aura'),
    (64, 'Kirlia', 'Pulsing Aura'),
    (65, 'Espurr', 'Pulsing Aura'),
    (66, 'Meowstic', 'Pulsing Aura'),
    (67, 'Diancie', 'Pulsing Aura'),
    (68, 'Oricorio', 'Pulsing Aura'),
    (69, 'Hatenna', 'Pulsing Aura'),
    (70, 'Hattrem', 'Pulsing Aura'),
    (71, 'Hatterene', 'Pulsing Aura'),
    (72, 'Bramblin', 'Pulsing Aura'),
    (73, 'Brambleghast', 'Pulsing Aura'),
    (74, 'Gligar', 'Pulsing Aura'),
    (75, 'Gliscor', 'Pulsing Aura'),
    (76, 'Trapinch', 'Pulsing Aura'),
    (77, 'Regirock', 'Pulsing Aura'),
    (78, 'Bonsly', 'Pulsing Aura'),
    (79, 'Riolu', 'Pulsing Aura'),
    (80, 'Lucario', 'Pulsing Aura'),
    (81, 'Mega Lucario ex', 'Pulsing Aura'),
    (82, 'Croagunk', 'Pulsing Aura'),
    (83, 'Toxicroak', 'Pulsing Aura'),
    (84, 'Gallade', 'Pulsing Aura'),
    (85, 'Throh', 'Pulsing Aura'),
    (86, 'Sawk', 'Pulsing Aura'),
    (87, 'Dwebble', 'Pulsing Aura'),
    (88, 'Crustle ex', 'Pulsing Aura'),
    (89, 'Meloetta', 'Pulsing Aura'),
    (90, 'Stufful', 'Pulsing Aura'),
    (91, 'Bewear', 'Pulsing Aura'),
    (92, 'Rolycoly', 'Pulsing Aura'),
    (93, 'Carkol', 'Pulsing Aura'),
    (94, 'Coalossal', 'Pulsing Aura'),
    (95, 'Silicobra', 'Pulsing Aura'),
    (96, 'Sandaconda', 'Pulsing Aura'),
    (97, 'Kubfu', 'Pulsing Aura'),
    (98, 'Zubat', 'Pulsing Aura'),
    (99, 'Golbat', 'Pulsing Aura'),
    (100, 'Crobat', 'Pulsing Aura'),
    (101, 'Koffing', 'Pulsing Aura'),
    (102, 'Weezing', 'Pulsing Aura'),
    (103, 'Qwilfish', 'Pulsing Aura'),
    (104, 'Seviper', 'Pulsing Aura'),
    (105, 'Zorua', 'Pulsing Aura'),
    (106, 'Zoroark ex', 'Pulsing Aura'),
    (107, 'Foongus', 'Pulsing Aura'),
    (108, 'Amoonguss', 'Pulsing Aura'),
    (109, 'Vullaby', 'Pulsing Aura'),
    (110, 'Mandibuzz', 'Pulsing Aura'),
    (111, 'Inkay', 'Pulsing Aura'),
    (112, 'Malamar', 'Pulsing Aura'),
    (113, 'Single Strike Urshifu', 'Pulsing Aura'),
    (114, 'Zarude', 'Pulsing Aura'),
    (115, 'Bombirdier', 'Pulsing Aura'),
    (116, 'Registeel', 'Pulsing Aura'),
    (117, 'Bronzor', 'Pulsing Aura'),
    (118, 'Bronzong', 'Pulsing Aura'),
    (119, 'Pawniard', 'Pulsing Aura'),
    (120, 'Bisharp', 'Pulsing Aura'),
    (121, 'Magearna', 'Pulsing Aura'),
    (122, 'Meltan', 'Pulsing Aura'),
    (123, 'Melmetal', 'Pulsing Aura'),
    (124, 'Corviknight ex', 'Pulsing Aura'),
    (125, 'Vibrava', 'Pulsing Aura'),
    (126, 'Flygon ex', 'Pulsing Aura'),
    (127, 'Chansey', 'Pulsing Aura'),
    (128, 'Blissey', 'Pulsing Aura'),
    (129, 'Eevee', 'Pulsing Aura'),
    (130, 'Dunsparce', 'Pulsing Aura'),
    (131, 'Teddiursa', 'Pulsing Aura'),
    (132, 'Ursaring', 'Pulsing Aura'),
    (133, 'Castform', 'Pulsing Aura'),
    (134, 'Regigigas', 'Pulsing Aura'),
    (135, 'Patrat', 'Pulsing Aura'),
    (136, 'Watchog', 'Pulsing Aura'),
    (137, 'Lillipup', 'Pulsing Aura'),
    (138, 'Herdier', 'Pulsing Aura'),
    (139, 'Stoutland', 'Pulsing Aura'),
    (140, 'Audino', 'Pulsing Aura'),
    (141, 'Mega Audino ex', 'Pulsing Aura'),
    (142, 'Minccino', 'Pulsing Aura'),
    (143, 'Cinccino', 'Pulsing Aura'),
    (144, 'Furfrou', 'Pulsing Aura'),
    (145, 'Rookidee', 'Pulsing Aura'),
    (146, 'Corvisquire', 'Pulsing Aura'),
    (147, 'Field Blower', 'Pulsing Aura'),
    (148, 'Lucky Egg', 'Pulsing Aura'),
    (149, 'Korrina', 'Pulsing Aura'),
    (150, 'Cabbie', 'Pulsing Aura'),
    (151, 'Cheren', 'Pulsing Aura'),
    (152, 'Parasol Lady', 'Pulsing Aura'),
    (153, 'Fragrant Forest', 'Pulsing Aura'),
    (154, 'Arena of Antiquity', 'Pulsing Aura'),
    (155, 'Bounded Field', 'Pulsing Aura'),
    (156, 'Treecko', 'Pulsing Aura'),
    (157, 'Grovyle', 'Pulsing Aura'),
    (158, 'Shroomish', 'Pulsing Aura'),
    (159, 'Budew', 'Pulsing Aura'),
    (160, 'Flapple', 'Pulsing Aura'),
    (161, 'Tepig', 'Pulsing Aura'),
    (162, 'Quagsire', 'Pulsing Aura'),
    (163, 'Zekrom', 'Pulsing Aura'),
    (164, 'Morpeko', 'Pulsing Aura'),
    (165, 'Meowstic', 'Pulsing Aura'),
    (166, 'Oricorio', 'Pulsing Aura'),
    (167, 'Brambleghast', 'Pulsing Aura'),
    (168, 'Bonsly', 'Pulsing Aura'),
    (169, 'Riolu', 'Pulsing Aura'),
    (170, 'Meloetta', 'Pulsing Aura'),
    (171, 'Carkol', 'Pulsing Aura'),
    (172, 'Kubfu', 'Pulsing Aura'),
    (173, 'Seviper', 'Pulsing Aura'),
    (174, 'Zorua', 'Pulsing Aura'),
    (175, 'Malamar', 'Pulsing Aura'),
    (176, 'Bisharp', 'Pulsing Aura'),
    (177, 'Meltan', 'Pulsing Aura'),
    (178, 'Castform', 'Pulsing Aura'),
    (179, 'Cinccino', 'Pulsing Aura'),
    (180, 'Mega Sceptile ex', 'Pulsing Aura'),
    (181, 'Mega Camerupt ex', 'Pulsing Aura'),
    (182, 'Vaporeon ex', 'Pulsing Aura'),
    (183, 'Magnezone ex', 'Pulsing Aura'),
    (184, 'Mega Lucario ex', 'Pulsing Aura'),
    (185, 'Crustle ex', 'Pulsing Aura'),
    (186, 'Zoroark ex', 'Pulsing Aura'),
    (187, 'Corviknight ex', 'Pulsing Aura'),
    (188, 'Flygon ex', 'Pulsing Aura'),
    (189, 'Mega Audino ex', 'Pulsing Aura'),
    (190, 'Korrina', 'Pulsing Aura'),
    (191, 'Cabbie', 'Pulsing Aura'),
    (192, 'Cheren', 'Pulsing Aura'),
    (193, 'Parasol Lady', 'Pulsing Aura'),
    (194, 'Mega Sceptile ex', 'Pulsing Aura'),
    (195, 'Mega Camerupt ex', 'Pulsing Aura'),
    (196, 'Vaporeon ex', 'Pulsing Aura'),
    (197, 'Magnezone ex', 'Pulsing Aura'),
    (198, 'Crustle ex', 'Pulsing Aura'),
    (199, 'Zoroark ex', 'Pulsing Aura'),
    (200, 'Corviknight ex', 'Pulsing Aura'),
    (201, 'Flygon ex', 'Pulsing Aura'),
    (202, 'Mega Audino ex', 'Pulsing Aura'),
    (203, 'Sobble', 'Pulsing Aura'),
    (204, 'Mega Lucario ex', 'Pulsing Aura'),
    (205, 'Cottonee', 'Pulsing Aura'),
    (206, 'Torchic', 'Pulsing Aura'),
    (207, 'Combusken', 'Pulsing Aura'),
    (208, 'Blaziken', 'Pulsing Aura'),
    (209, 'Frillish', 'Pulsing Aura'),
    (210, 'Jellicent', 'Pulsing Aura'),
    (211, 'Onix', 'Pulsing Aura'),
    (212, 'Zubat', 'Pulsing Aura'),
    (213, 'Golbat', 'Pulsing Aura'),
    (214, 'Crobat', 'Pulsing Aura'),
    (215, 'Grimer', 'Pulsing Aura'),
    (216, 'Muk', 'Pulsing Aura'),
    (217, 'Absol', 'Pulsing Aura'),
    (218, 'Skrelp', 'Pulsing Aura'),
    (219, 'Steelix', 'Pulsing Aura'),
    (220, 'Chansey', 'Pulsing Aura'),
    (221, 'Blissey', 'Pulsing Aura'),
    (222, 'Porygon', 'Pulsing Aura'),
    (223, 'Porygon2', 'Pulsing Aura'),
    (224, 'Porygon-Z', 'Pulsing Aura'),
    (225, 'Whimsicott ex', 'Pulsing Aura'),
    (226, 'Mega Blaziken ex', 'Pulsing Aura'),
    (227, 'Greninja ex', 'Pulsing Aura'),
    (228, 'Jolteon ex', 'Pulsing Aura'),
    (229, 'Hitmonchan ex', 'Pulsing Aura'),
    (230, 'Mega Absol ex', 'Pulsing Aura'),
    (231, 'Dragalge ex', 'Pulsing Aura'),
    (232, 'Mega Steelix ex', 'Pulsing Aura'),
    (233, 'Celebi', 'Pulsing Aura'),
    (234, 'Bombirdier', 'Pulsing Aura')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
