-- Paradox Drive (B3a) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B3a
-- Limitless lists Paradox Drive as B3a with 109 cards.
-- Paradox Drive has one booster pack, represented here as Paradox Drive.

insert into public.cards (id, name, pack, image)
select
  'B3a-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3a/B3a_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Surskit', 'Paradox Drive'),
    (2, 'Masquerain', 'Paradox Drive'),
    (3, 'Brute Bonnet', 'Paradox Drive'),
    (4, 'Slither Wing', 'Paradox Drive'),
    (5, 'Iron Moth', 'Paradox Drive'),
    (6, 'Psyduck', 'Paradox Drive'),
    (7, 'Golduck', 'Paradox Drive'),
    (8, 'Vaporeon', 'Paradox Drive'),
    (9, 'Buizel', 'Paradox Drive'),
    (10, 'Floatzel', 'Paradox Drive'),
    (11, 'Snom', 'Paradox Drive'),
    (12, 'Frosmoth', 'Paradox Drive'),
    (13, 'Iron Bundle ex', 'Paradox Drive'),
    (14, 'Pawmi', 'Paradox Drive'),
    (15, 'Pawmo', 'Paradox Drive'),
    (16, 'Pawmot', 'Paradox Drive'),
    (17, 'Iron Hands', 'Paradox Drive'),
    (18, 'Iron Thorns', 'Paradox Drive'),
    (19, 'Miraidon ex', 'Paradox Drive'),
    (20, 'Espeon', 'Paradox Drive'),
    (21, 'Flittle', 'Paradox Drive'),
    (22, 'Espathra', 'Paradox Drive'),
    (23, 'Greavard', 'Paradox Drive'),
    (24, 'Houndstone', 'Paradox Drive'),
    (25, 'Scream Tail', 'Paradox Drive'),
    (26, 'Flutter Mane ex', 'Paradox Drive'),
    (27, 'Iron Valiant', 'Paradox Drive'),
    (28, 'Iron Leaves', 'Paradox Drive'),
    (29, 'Iron Boulder', 'Paradox Drive'),
    (30, 'Iron Crown', 'Paradox Drive'),
    (31, 'Nacli', 'Paradox Drive'),
    (32, 'Naclstack', 'Paradox Drive'),
    (33, 'Garganacl', 'Paradox Drive'),
    (34, 'Great Tusk', 'Paradox Drive'),
    (35, 'Sandy Shocks', 'Paradox Drive'),
    (36, 'Koraidon ex', 'Paradox Drive'),
    (37, 'Umbreon', 'Paradox Drive'),
    (38, 'Sneasel', 'Paradox Drive'),
    (39, 'Weavile', 'Paradox Drive'),
    (40, 'Sableye', 'Paradox Drive'),
    (41, 'Pawniard', 'Paradox Drive'),
    (42, 'Bisharp', 'Paradox Drive'),
    (43, 'Kingambit', 'Paradox Drive'),
    (44, 'Glimmet', 'Paradox Drive'),
    (45, 'Glimmora', 'Paradox Drive'),
    (46, 'Iron Jugulis', 'Paradox Drive'),
    (47, 'Roaring Moon', 'Paradox Drive'),
    (48, 'Corviknight', 'Paradox Drive'),
    (49, 'Cufant', 'Paradox Drive'),
    (50, 'Copperajah', 'Paradox Drive'),
    (51, 'Iron Treads', 'Paradox Drive'),
    (52, 'Altaria', 'Paradox Drive'),
    (53, 'Walking Wake', 'Paradox Drive'),
    (54, 'Gouging Fire', 'Paradox Drive'),
    (55, 'Raging Bolt', 'Paradox Drive'),
    (56, 'Eevee', 'Paradox Drive'),
    (57, 'Girafarig', 'Paradox Drive'),
    (58, 'Farigiraf', 'Paradox Drive'),
    (59, 'Dunsparce', 'Paradox Drive'),
    (60, 'Dudunsparce', 'Paradox Drive'),
    (61, 'Swablu', 'Paradox Drive'),
    (62, 'Rufflet', 'Paradox Drive'),
    (63, 'Braviary', 'Paradox Drive'),
    (64, 'Hawlucha', 'Paradox Drive'),
    (65, 'Rookidee', 'Paradox Drive'),
    (66, 'Corvisquire', 'Paradox Drive'),
    (67, 'Flamigo', 'Paradox Drive'),
    (68, 'Terapagos ex', 'Paradox Drive'),
    (69, 'Ancient Booster Energy Capsule', 'Paradox Drive'),
    (70, 'Future Booster Energy Capsule', 'Paradox Drive'),
    (71, 'Juliana', 'Paradox Drive'),
    (72, 'Professor Sada', 'Paradox Drive'),
    (73, 'Professor Turo', 'Paradox Drive'),
    (74, 'Area Zero', 'Paradox Drive'),
    (75, 'Snom', 'Paradox Drive'),
    (76, 'Flittle', 'Paradox Drive'),
    (77, 'Iron Boulder', 'Paradox Drive'),
    (78, 'Glimmora', 'Paradox Drive'),
    (79, 'Raging Bolt', 'Paradox Drive'),
    (80, 'Hawlucha', 'Paradox Drive'),
    (81, 'Iron Bundle ex', 'Paradox Drive'),
    (82, 'Miraidon ex', 'Paradox Drive'),
    (83, 'Flutter Mane ex', 'Paradox Drive'),
    (84, 'Koraidon ex', 'Paradox Drive'),
    (85, 'Terapagos ex', 'Paradox Drive'),
    (86, 'Juliana', 'Paradox Drive'),
    (87, 'Professor Sada', 'Paradox Drive'),
    (88, 'Professor Turo', 'Paradox Drive'),
    (89, 'Iron Bundle ex', 'Paradox Drive'),
    (90, 'Miraidon ex', 'Paradox Drive'),
    (91, 'Flutter Mane ex', 'Paradox Drive'),
    (92, 'Koraidon ex', 'Paradox Drive'),
    (93, 'Terapagos ex', 'Paradox Drive'),
    (94, 'Rellor', 'Paradox Drive'),
    (95, 'Charcadet', 'Paradox Drive'),
    (96, 'Tadbulb', 'Paradox Drive'),
    (97, 'Rabsca', 'Paradox Drive'),
    (98, 'Diglett', 'Paradox Drive'),
    (99, 'Dugtrio', 'Paradox Drive'),
    (100, 'Klawf', 'Paradox Drive'),
    (101, 'Orthworm', 'Paradox Drive'),
    (102, 'Swablu', 'Paradox Drive'),
    (103, 'Altaria', 'Paradox Drive'),
    (104, 'Meowscarada ex', 'Paradox Drive'),
    (105, 'Armarouge ex', 'Paradox Drive'),
    (106, 'Bellibolt ex', 'Paradox Drive'),
    (107, 'Mega Altaria ex', 'Paradox Drive'),
    (108, 'Iron Valiant', 'Paradox Drive'),
    (109, 'Roaring Moon', 'Paradox Drive')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
