-- Ruler of the Skies (B4) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B4
-- Limitless lists Ruler of the Skies as B4 with 233 cards.
-- Ruler of the Skies has one booster pack, represented here as Ruler of the Skies.

insert into public.cards (id, name, pack, image)
select
  'B4-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B4/B4_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Wurmple', 'Ruler of the Skies'),
    (2, 'Silcoon', 'Ruler of the Skies'),
    (3, 'Beautifly', 'Ruler of the Skies'),
    (4, 'Cascoon', 'Ruler of the Skies'),
    (5, 'Dustox', 'Ruler of the Skies'),
    (6, 'Lileep', 'Ruler of the Skies'),
    (7, 'Cradily', 'Ruler of the Skies'),
    (8, 'Kricketot', 'Ruler of the Skies'),
    (9, 'Kricketune', 'Ruler of the Skies'),
    (10, 'Combee', 'Ruler of the Skies'),
    (11, 'Vespiquen ex', 'Ruler of the Skies'),
    (12, 'Karrablast', 'Ruler of the Skies'),
    (13, 'Shelmet', 'Ruler of the Skies'),
    (14, 'Accelgor', 'Ruler of the Skies'),
    (15, 'Dhelmise', 'Ruler of the Skies'),
    (16, 'Pheromosa', 'Ruler of the Skies'),
    (17, 'Poltchageist', 'Ruler of the Skies'),
    (18, 'Sinistcha', 'Ruler of the Skies'),
    (19, 'Teal Mask Ogerpon', 'Ruler of the Skies'),
    (20, 'Ponyta', 'Ruler of the Skies'),
    (21, 'Rapidash', 'Ruler of the Skies'),
    (22, 'Flareon', 'Ruler of the Skies'),
    (23, 'Moltres', 'Ruler of the Skies'),
    (24, 'Cyndaquil', 'Ruler of the Skies'),
    (25, 'Quilava', 'Ruler of the Skies'),
    (26, 'Typhlosion ex', 'Ruler of the Skies'),
    (27, 'Houndour', 'Ruler of the Skies'),
    (28, 'Houndoom', 'Ruler of the Skies'),
    (29, 'Heatmor', 'Ruler of the Skies'),
    (30, 'Psyduck', 'Ruler of the Skies'),
    (31, 'Golduck', 'Ruler of the Skies'),
    (32, 'Staryu', 'Ruler of the Skies'),
    (33, 'Starmie', 'Ruler of the Skies'),
    (34, 'Carvanha', 'Ruler of the Skies'),
    (35, 'Mega Sharpedo ex', 'Ruler of the Skies'),
    (36, 'Wailmer', 'Ruler of the Skies'),
    (37, 'Wailord ex', 'Ruler of the Skies'),
    (38, 'Spheal', 'Ruler of the Skies'),
    (39, 'Sealeo', 'Ruler of the Skies'),
    (40, 'Walrein', 'Ruler of the Skies'),
    (41, 'Kyogre', 'Ruler of the Skies'),
    (42, 'Oshawott', 'Ruler of the Skies'),
    (43, 'Dewott', 'Ruler of the Skies'),
    (44, 'Samurott', 'Ruler of the Skies'),
    (45, 'Alomomola', 'Ruler of the Skies'),
    (46, 'Dewpider', 'Ruler of the Skies'),
    (47, 'Araquanid', 'Ruler of the Skies'),
    (48, 'Bruxish', 'Ruler of the Skies'),
    (49, 'Pikachu', 'Ruler of the Skies'),
    (50, 'Raichu', 'Ruler of the Skies'),
    (51, 'Shinx', 'Ruler of the Skies'),
    (52, 'Luxio', 'Ruler of the Skies'),
    (53, 'Luxray', 'Ruler of the Skies'),
    (54, 'Pachirisu', 'Ruler of the Skies'),
    (55, 'Rotom ex', 'Ruler of the Skies'),
    (56, 'Tynamo', 'Ruler of the Skies'),
    (57, 'Eelektrik', 'Ruler of the Skies'),
    (58, 'Eelektross', 'Ruler of the Skies'),
    (59, 'Thundurus', 'Ruler of the Skies'),
    (60, 'Helioptile', 'Ruler of the Skies'),
    (61, 'Heliolisk', 'Ruler of the Skies'),
    (62, 'Wattrel', 'Ruler of the Skies'),
    (63, 'Kilowattrel', 'Ruler of the Skies'),
    (64, 'Clefairy', 'Ruler of the Skies'),
    (65, 'Clefable', 'Ruler of the Skies'),
    (66, 'Drowzee', 'Ruler of the Skies'),
    (67, 'Hypno', 'Ruler of the Skies'),
    (68, 'Mime Jr.', 'Ruler of the Skies'),
    (69, 'Mr. Mime', 'Ruler of the Skies'),
    (70, 'Mewtwo', 'Ruler of the Skies'),
    (71, 'Ralts', 'Ruler of the Skies'),
    (72, 'Kirlia', 'Ruler of the Skies'),
    (73, 'Chimecho', 'Ruler of the Skies'),
    (74, 'Wynaut', 'Ruler of the Skies'),
    (75, 'Woobat', 'Ruler of the Skies'),
    (76, 'Swoobat', 'Ruler of the Skies'),
    (77, 'Hoopa', 'Ruler of the Skies'),
    (78, 'Oricorio', 'Ruler of the Skies'),
    (79, 'Makuhita', 'Ruler of the Skies'),
    (80, 'Hariyama', 'Ruler of the Skies'),
    (81, 'Anorith', 'Ruler of the Skies'),
    (82, 'Armaldo', 'Ruler of the Skies'),
    (83, 'Groudon', 'Ruler of the Skies'),
    (84, 'Mega Gallade ex', 'Ruler of the Skies'),
    (85, 'Drilbur', 'Ruler of the Skies'),
    (86, 'Excadrill', 'Ruler of the Skies'),
    (87, 'Timburr', 'Ruler of the Skies'),
    (88, 'Gurdurr', 'Ruler of the Skies'),
    (89, 'Conkeldurr', 'Ruler of the Skies'),
    (90, 'Minior', 'Ruler of the Skies'),
    (91, 'Grimer', 'Ruler of the Skies'),
    (92, 'Muk', 'Ruler of the Skies'),
    (93, 'Poochyena', 'Ruler of the Skies'),
    (94, 'Mightyena', 'Ruler of the Skies'),
    (95, 'Galarian Zigzagoon', 'Ruler of the Skies'),
    (96, 'Galarian Linoone', 'Ruler of the Skies'),
    (97, 'Galarian Obstagoon', 'Ruler of the Skies'),
    (98, 'Gulpin', 'Ruler of the Skies'),
    (99, 'Swalot', 'Ruler of the Skies'),
    (100, 'Absol', 'Ruler of the Skies'),
    (101, 'Vullaby', 'Ruler of the Skies'),
    (102, 'Mandibuzz', 'Ruler of the Skies'),
    (103, 'Hoopa ex', 'Ruler of the Skies'),
    (104, 'Skarmory', 'Ruler of the Skies'),
    (105, 'Mawile', 'Ruler of the Skies'),
    (106, 'Beldum', 'Ruler of the Skies'),
    (107, 'Metang', 'Ruler of the Skies'),
    (108, 'Metagross', 'Ruler of the Skies'),
    (109, 'Mega Metagross ex', 'Ruler of the Skies'),
    (110, 'Escavalier', 'Ruler of the Skies'),
    (111, 'Genesect', 'Ruler of the Skies'),
    (112, 'Duraludon', 'Ruler of the Skies'),
    (113, 'Archaludon', 'Ruler of the Skies'),
    (114, 'Varoom', 'Ruler of the Skies'),
    (115, 'Revavroom', 'Ruler of the Skies'),
    (116, 'Dratini', 'Ruler of the Skies'),
    (117, 'Dragonair', 'Ruler of the Skies'),
    (118, 'Dragonite', 'Ruler of the Skies'),
    (119, 'Rayquaza', 'Ruler of the Skies'),
    (120, 'Mega Rayquaza ex', 'Ruler of the Skies'),
    (121, 'Noibat', 'Ruler of the Skies'),
    (122, 'Noivern', 'Ruler of the Skies'),
    (123, 'Turtonator', 'Ruler of the Skies'),
    (124, 'Drampa', 'Ruler of the Skies'),
    (125, 'Applin', 'Ruler of the Skies'),
    (126, 'Dipplin', 'Ruler of the Skies'),
    (127, 'Hydrapple', 'Ruler of the Skies'),
    (128, 'Cyclizar', 'Ruler of the Skies'),
    (129, 'Rattata', 'Ruler of the Skies'),
    (130, 'Raticate', 'Ruler of the Skies'),
    (131, 'Eevee', 'Ruler of the Skies'),
    (132, 'Aipom', 'Ruler of the Skies'),
    (133, 'Ambipom', 'Ruler of the Skies'),
    (134, 'Skitty', 'Ruler of the Skies'),
    (135, 'Delcatty', 'Ruler of the Skies'),
    (136, 'Kecleon', 'Ruler of the Skies'),
    (137, 'Pidove', 'Ruler of the Skies'),
    (138, 'Tranquill', 'Ruler of the Skies'),
    (139, 'Unfezant', 'Ruler of the Skies'),
    (140, 'Ducklett', 'Ruler of the Skies'),
    (141, 'Swanna ex', 'Ruler of the Skies'),
    (142, 'Furfrou', 'Ruler of the Skies'),
    (143, 'Type: Null', 'Ruler of the Skies'),
    (144, 'Silvally', 'Ruler of the Skies'),
    (145, 'Order Pad', 'Ruler of the Skies'),
    (146, 'Claw Fossil', 'Ruler of the Skies'),
    (147, 'Root Fossil', 'Ruler of the Skies'),
    (148, 'Deceptive Needle', 'Ruler of the Skies'),
    (149, 'Clear Veil', 'Ruler of the Skies'),
    (150, 'Psychic', 'Ruler of the Skies'),
    (151, 'Drayden', 'Ruler of the Skies'),
    (152, 'Skyla', 'Ruler of the Skies'),
    (153, 'Wally', 'Ruler of the Skies'),
    (154, 'Soothing Shore', 'Ruler of the Skies'),
    (155, 'Rainbow Cave', 'Ruler of the Skies'),
    (156, 'Wurmple', 'Ruler of the Skies'),
    (157, 'Lileep', 'Ruler of the Skies'),
    (158, 'Kricketune', 'Ruler of the Skies'),
    (159, 'Accelgor', 'Ruler of the Skies'),
    (160, 'Ponyta', 'Ruler of the Skies'),
    (161, 'Quilava', 'Ruler of the Skies'),
    (162, 'Kyogre', 'Ruler of the Skies'),
    (163, 'Samurott', 'Ruler of the Skies'),
    (164, 'Raichu', 'Ruler of the Skies'),
    (165, 'Wattrel', 'Ruler of the Skies'),
    (166, 'Clefairy', 'Ruler of the Skies'),
    (167, 'Ralts', 'Ruler of the Skies'),
    (168, 'Wynaut', 'Ruler of the Skies'),
    (169, 'Oricorio', 'Ruler of the Skies'),
    (170, 'Anorith', 'Ruler of the Skies'),
    (171, 'Poochyena', 'Ruler of the Skies'),
    (172, 'Gulpin', 'Ruler of the Skies'),
    (173, 'Vullaby', 'Ruler of the Skies'),
    (174, 'Genesect', 'Ruler of the Skies'),
    (175, 'Dragonair', 'Ruler of the Skies'),
    (176, 'Noivern', 'Ruler of the Skies'),
    (177, 'Cyclizar', 'Ruler of the Skies'),
    (178, 'Raticate', 'Ruler of the Skies'),
    (179, 'Aipom', 'Ruler of the Skies'),
    (180, 'Vespiquen ex', 'Ruler of the Skies'),
    (181, 'Typhlosion ex', 'Ruler of the Skies'),
    (182, 'Mega Sharpedo ex', 'Ruler of the Skies'),
    (183, 'Wailord ex', 'Ruler of the Skies'),
    (184, 'Rotom ex', 'Ruler of the Skies'),
    (185, 'Mega Gallade ex', 'Ruler of the Skies'),
    (186, 'Hoopa ex', 'Ruler of the Skies'),
    (187, 'Mega Metagross ex', 'Ruler of the Skies'),
    (188, 'Mega Rayquaza ex', 'Ruler of the Skies'),
    (189, 'Swanna ex', 'Ruler of the Skies'),
    (190, 'Psychic', 'Ruler of the Skies'),
    (191, 'Drayden', 'Ruler of the Skies'),
    (192, 'Skyla', 'Ruler of the Skies'),
    (193, 'Wally', 'Ruler of the Skies'),
    (194, 'Vespiquen ex', 'Ruler of the Skies'),
    (195, 'Typhlosion ex', 'Ruler of the Skies'),
    (196, 'Mega Sharpedo ex', 'Ruler of the Skies'),
    (197, 'Wailord ex', 'Ruler of the Skies'),
    (198, 'Mega Gallade ex', 'Ruler of the Skies'),
    (199, 'Hoopa ex', 'Ruler of the Skies'),
    (200, 'Mega Metagross ex', 'Ruler of the Skies'),
    (201, 'Swanna ex', 'Ruler of the Skies'),
    (202, 'Rotom ex', 'Ruler of the Skies'),
    (203, 'Mega Rayquaza ex', 'Ruler of the Skies'),
    (204, 'Alolan Vulpix', 'Ruler of the Skies'),
    (205, 'Mudkip', 'Ruler of the Skies'),
    (206, 'Marshtomp', 'Ruler of the Skies'),
    (207, 'Swampert', 'Ruler of the Skies'),
    (208, 'Electabuzz', 'Ruler of the Skies'),
    (209, 'Plusle', 'Ruler of the Skies'),
    (210, 'Minun', 'Ruler of the Skies'),
    (211, 'Mr. Mime', 'Ruler of the Skies'),
    (212, 'Mewtwo', 'Ruler of the Skies'),
    (213, 'Roggenrola', 'Ruler of the Skies'),
    (214, 'Boldore', 'Ruler of the Skies'),
    (215, 'Falinks', 'Ruler of the Skies'),
    (216, 'Koffing', 'Ruler of the Skies'),
    (217, 'Weezing', 'Ruler of the Skies'),
    (218, 'Galarian Meowth', 'Ruler of the Skies'),
    (219, 'Galarian Perrserker', 'Ruler of the Skies'),
    (220, 'Rattata', 'Ruler of the Skies'),
    (221, 'Raticate', 'Ruler of the Skies'),
    (222, 'Smeargle', 'Ruler of the Skies'),
    (223, 'Buneary', 'Ruler of the Skies'),
    (224, 'Blacephalon ex', 'Ruler of the Skies'),
    (225, 'Alolan Ninetales ex', 'Ruler of the Skies'),
    (226, 'Mega Swampert ex', 'Ruler of the Skies'),
    (227, 'Mega Gardevoir ex', 'Ruler of the Skies'),
    (228, 'Mega Lopunny ex', 'Ruler of the Skies'),
    (229, 'Gigalith ex', 'Ruler of the Skies'),
    (230, 'Zoroark ex', 'Ruler of the Skies'),
    (231, 'Mega Kangaskhan ex', 'Ruler of the Skies'),
    (232, 'Raichu', 'Ruler of the Skies'),
    (233, 'Dragonair', 'Ruler of the Skies')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
