-- Genetic Apex (A1) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A1
-- Limitless lists Genetic Apex as A1, released 30th October 2024, with 286 cards.
-- Pack values are derived from the Limitless A1 pack filters:
-- Charizard, Mewtwo, Pikachu, and Shared.

insert into public.cards (id, name, pack, image)
select
  'A1-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1/A1_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Bulbasaur', 'Mewtwo'),
    (2, 'Ivysaur', 'Mewtwo'),
    (3, 'Venusaur', 'Mewtwo'),
    (4, 'Venusaur ex', 'Mewtwo'),
    (5, 'Caterpie', 'Pikachu'),
    (6, 'Metapod', 'Pikachu'),
    (7, 'Butterfree', 'Pikachu'),
    (8, 'Weedle', 'Mewtwo'),
    (9, 'Kakuna', 'Mewtwo'),
    (10, 'Beedrill', 'Mewtwo'),
    (11, 'Oddish', 'Charizard'),
    (12, 'Gloom', 'Charizard'),
    (13, 'Vileplume', 'Charizard'),
    (14, 'Paras', 'Pikachu'),
    (15, 'Parasect', 'Pikachu'),
    (16, 'Venonat', 'Mewtwo'),
    (17, 'Venomoth', 'Mewtwo'),
    (18, 'Bellsprout', 'Charizard'),
    (19, 'Weepinbell', 'Charizard'),
    (20, 'Victreebel', 'Charizard'),
    (21, 'Exeggcute', 'Charizard'),
    (22, 'Exeggutor', 'Charizard'),
    (23, 'Exeggutor ex', 'Charizard'),
    (24, 'Tangela', 'Charizard'),
    (25, 'Scyther', 'Mewtwo'),
    (26, 'Pinsir', 'Shared'),
    (27, 'Cottonee', 'Shared'),
    (28, 'Whimsicott', 'Shared'),
    (29, 'Petilil', 'Shared'),
    (30, 'Lilligant', 'Shared'),
    (31, 'Skiddo', 'Charizard'),
    (32, 'Gogoat', 'Charizard'),
    (33, 'Charmander', 'Charizard'),
    (34, 'Charmeleon', 'Charizard'),
    (35, 'Charizard', 'Charizard'),
    (36, 'Charizard ex', 'Charizard'),
    (37, 'Vulpix', 'Charizard'),
    (38, 'Ninetales', 'Charizard'),
    (39, 'Growlithe', 'Pikachu'),
    (40, 'Arcanine', 'Pikachu'),
    (41, 'Arcanine ex', 'Pikachu'),
    (42, 'Ponyta', 'Shared'),
    (43, 'Rapidash', 'Shared'),
    (44, 'Magmar', 'Charizard'),
    (45, 'Flareon', 'Charizard'),
    (46, 'Moltres', 'Charizard'),
    (47, 'Moltres ex', 'Charizard'),
    (48, 'Heatmor', 'Shared'),
    (49, 'Salandit', 'Mewtwo'),
    (50, 'Salazzle', 'Mewtwo'),
    (51, 'Sizzlipede', 'Shared'),
    (52, 'Centiskorch', 'Shared'),
    (53, 'Squirtle', 'Pikachu'),
    (54, 'Wartortle', 'Pikachu'),
    (55, 'Blastoise', 'Pikachu'),
    (56, 'Blastoise ex', 'Pikachu'),
    (57, 'Psyduck', 'Shared'),
    (58, 'Golduck', 'Shared'),
    (59, 'Poliwag', 'Charizard'),
    (60, 'Poliwhirl', 'Charizard'),
    (61, 'Poliwrath', 'Charizard'),
    (62, 'Tentacool', 'Mewtwo'),
    (63, 'Tentacruel', 'Mewtwo'),
    (64, 'Seel', 'Pikachu'),
    (65, 'Dewgong', 'Pikachu'),
    (66, 'Shellder', 'Mewtwo'),
    (67, 'Cloyster', 'Mewtwo'),
    (68, 'Krabby', 'Mewtwo'),
    (69, 'Kingler', 'Mewtwo'),
    (70, 'Horsea', 'Pikachu'),
    (71, 'Seadra', 'Pikachu'),
    (72, 'Goldeen', 'Pikachu'),
    (73, 'Seaking', 'Pikachu'),
    (74, 'Staryu', 'Charizard'),
    (75, 'Starmie', 'Charizard'),
    (76, 'Starmie ex', 'Charizard'),
    (77, 'Magikarp', 'Pikachu'),
    (78, 'Gyarados', 'Pikachu'),
    (79, 'Lapras', 'Charizard'),
    (80, 'Vaporeon', 'Mewtwo'),
    (81, 'Omanyte', 'Pikachu'),
    (82, 'Omastar', 'Pikachu'),
    (83, 'Articuno', 'Mewtwo'),
    (84, 'Articuno ex', 'Mewtwo'),
    (85, 'Ducklett', 'Charizard'),
    (86, 'Swanna', 'Charizard'),
    (87, 'Froakie', 'Charizard'),
    (88, 'Frogadier', 'Charizard'),
    (89, 'Greninja', 'Charizard'),
    (90, 'Pyukumuku', 'Charizard'),
    (91, 'Bruxish', 'Shared'),
    (92, 'Snom', 'Shared'),
    (93, 'Frosmoth', 'Shared'),
    (94, 'Pikachu', 'Pikachu'),
    (95, 'Raichu', 'Pikachu'),
    (96, 'Pikachu ex', 'Pikachu'),
    (97, 'Magnemite', 'Pikachu'),
    (98, 'Magneton', 'Pikachu'),
    (99, 'Voltorb', 'Pikachu'),
    (100, 'Electrode', 'Pikachu'),
    (101, 'Electabuzz', 'Pikachu'),
    (102, 'Jolteon', 'Pikachu'),
    (103, 'Zapdos', 'Pikachu'),
    (104, 'Zapdos ex', 'Pikachu'),
    (105, 'Blitzle', 'Shared'),
    (106, 'Zebstrika', 'Shared'),
    (107, 'Tynamo', 'Mewtwo'),
    (108, 'Eelektrik', 'Mewtwo'),
    (109, 'Eelektross', 'Mewtwo'),
    (110, 'Helioptile', 'Shared'),
    (111, 'Heliolisk', 'Shared'),
    (112, 'Pincurchin', 'Shared'),
    (113, 'Clefairy', 'Pikachu'),
    (114, 'Clefable', 'Pikachu'),
    (115, 'Abra', 'Charizard'),
    (116, 'Kadabra', 'Charizard'),
    (117, 'Alakazam', 'Charizard'),
    (118, 'Slowpoke', 'Shared'),
    (119, 'Slowbro', 'Shared'),
    (120, 'Gastly', 'Mewtwo'),
    (121, 'Haunter', 'Mewtwo'),
    (122, 'Gengar', 'Mewtwo'),
    (123, 'Gengar ex', 'Mewtwo'),
    (124, 'Drowzee', 'Pikachu'),
    (125, 'Hypno', 'Pikachu'),
    (126, 'Mr. Mime', 'Mewtwo'),
    (127, 'Jynx', 'Mewtwo'),
    (128, 'Mewtwo', 'Mewtwo'),
    (129, 'Mewtwo ex', 'Mewtwo'),
    (130, 'Ralts', 'Mewtwo'),
    (131, 'Kirlia', 'Mewtwo'),
    (132, 'Gardevoir', 'Mewtwo'),
    (133, 'Woobat', 'Shared'),
    (134, 'Swoobat', 'Shared'),
    (135, 'Golett', 'Shared'),
    (136, 'Golurk', 'Shared'),
    (137, 'Sandshrew', 'Shared'),
    (138, 'Sandslash', 'Shared'),
    (139, 'Diglett', 'Pikachu'),
    (140, 'Dugtrio', 'Pikachu'),
    (141, 'Mankey', 'Charizard'),
    (142, 'Primeape', 'Charizard'),
    (143, 'Machop', 'Charizard'),
    (144, 'Machoke', 'Charizard'),
    (145, 'Machamp', 'Charizard'),
    (146, 'Machamp ex', 'Charizard'),
    (147, 'Geodude', 'Pikachu'),
    (148, 'Graveler', 'Pikachu'),
    (149, 'Golem', 'Pikachu'),
    (150, 'Onix', 'Pikachu'),
    (151, 'Cubone', 'Mewtwo'),
    (152, 'Marowak', 'Mewtwo'),
    (153, 'Marowak ex', 'Mewtwo'),
    (154, 'Hitmonlee', 'Mewtwo'),
    (155, 'Hitmonchan', 'Charizard'),
    (156, 'Rhyhorn', 'Mewtwo'),
    (157, 'Rhydon', 'Mewtwo'),
    (158, 'Kabuto', 'Charizard'),
    (159, 'Kabutops', 'Charizard'),
    (160, 'Mienfoo', 'Pikachu'),
    (161, 'Mienshao', 'Pikachu'),
    (162, 'Clobbopus', 'Shared'),
    (163, 'Grapploct', 'Shared'),
    (164, 'Ekans', 'Shared'),
    (165, 'Arbok', 'Shared'),
    (166, 'Nidoran♀', 'Pikachu'),
    (167, 'Nidorina', 'Pikachu'),
    (168, 'Nidoqueen', 'Pikachu'),
    (169, 'Nidoran♂', 'Pikachu'),
    (170, 'Nidorino', 'Pikachu'),
    (171, 'Nidoking', 'Pikachu'),
    (172, 'Zubat', 'Mewtwo'),
    (173, 'Golbat', 'Mewtwo'),
    (174, 'Grimer', 'Mewtwo'),
    (175, 'Muk', 'Mewtwo'),
    (176, 'Koffing', 'Mewtwo'),
    (177, 'Weezing', 'Mewtwo'),
    (178, 'Mawile', 'Charizard'),
    (179, 'Pawniard', 'Shared'),
    (180, 'Bisharp', 'Shared'),
    (181, 'Meltan', 'Charizard'),
    (182, 'Melmetal', 'Charizard'),
    (183, 'Dratini', 'Mewtwo'),
    (184, 'Dragonair', 'Mewtwo'),
    (185, 'Dragonite', 'Mewtwo'),
    (186, 'Pidgey', 'Mewtwo'),
    (187, 'Pidgeotto', 'Mewtwo'),
    (188, 'Pidgeot', 'Mewtwo'),
    (189, 'Rattata', 'Shared'),
    (190, 'Raticate', 'Shared'),
    (191, 'Spearow', 'Charizard'),
    (192, 'Fearow', 'Charizard'),
    (193, 'Jigglypuff', 'Pikachu'),
    (194, 'Wigglytuff', 'Pikachu'),
    (195, 'Wigglytuff ex', 'Pikachu'),
    (196, 'Meowth', 'Charizard'),
    (197, 'Persian', 'Charizard'),
    (198, 'Farfetch''d', 'Shared'),
    (199, 'Doduo', 'Shared'),
    (200, 'Dodrio', 'Shared'),
    (201, 'Lickitung', 'Mewtwo'),
    (202, 'Chansey', 'Pikachu'),
    (203, 'Kangaskhan', 'Charizard'),
    (204, 'Tauros', 'Charizard'),
    (205, 'Ditto', 'Mewtwo'),
    (206, 'Eevee', 'Charizard'),
    (207, 'Eevee', 'Mewtwo'),
    (208, 'Eevee', 'Pikachu'),
    (209, 'Porygon', 'Mewtwo'),
    (210, 'Aerodactyl', 'Mewtwo'),
    (211, 'Snorlax', 'Pikachu'),
    (212, 'Minccino', 'Shared'),
    (213, 'Cinccino', 'Shared'),
    (214, 'Wooloo', 'Shared'),
    (215, 'Dubwool', 'Shared'),
    (216, 'Helix Fossil', 'Pikachu'),
    (217, 'Dome Fossil', 'Charizard'),
    (218, 'Old Amber', 'Mewtwo'),
    (219, 'Erika', 'Charizard'),
    (220, 'Misty', 'Pikachu'),
    (221, 'Blaine', 'Charizard'),
    (222, 'Koga', 'Mewtwo'),
    (223, 'Giovanni', 'Mewtwo'),
    (224, 'Brock', 'Pikachu'),
    (225, 'Sabrina', 'Charizard'),
    (226, 'Lt. Surge', 'Pikachu'),
    (227, 'Bulbasaur', 'Mewtwo'),
    (228, 'Gloom', 'Charizard'),
    (229, 'Pinsir', 'Charizard'),
    (230, 'Charmander', 'Charizard'),
    (231, 'Rapidash', 'Charizard'),
    (232, 'Squirtle', 'Pikachu'),
    (233, 'Gyarados', 'Pikachu'),
    (234, 'Lapras', 'Charizard'),
    (235, 'Electrode', 'Pikachu'),
    (236, 'Alakazam', 'Charizard'),
    (237, 'Slowpoke', 'Charizard'),
    (238, 'Diglett', 'Pikachu'),
    (239, 'Cubone', 'Mewtwo'),
    (240, 'Nidoqueen', 'Pikachu'),
    (241, 'Nidoking', 'Pikachu'),
    (242, 'Golbat', 'Mewtwo'),
    (243, 'Weezing', 'Mewtwo'),
    (244, 'Dragonite', 'Mewtwo'),
    (245, 'Pidgeot', 'Mewtwo'),
    (246, 'Meowth', 'Charizard'),
    (247, 'Ditto', 'Mewtwo'),
    (248, 'Eevee', 'Pikachu'),
    (249, 'Porygon', 'Mewtwo'),
    (250, 'Snorlax', 'Pikachu'),
    (251, 'Venusaur ex', 'Mewtwo'),
    (252, 'Exeggutor ex', 'Charizard'),
    (253, 'Charizard ex', 'Charizard'),
    (254, 'Arcanine ex', 'Pikachu'),
    (255, 'Moltres ex', 'Charizard'),
    (256, 'Blastoise ex', 'Pikachu'),
    (257, 'Starmie ex', 'Charizard'),
    (258, 'Articuno ex', 'Mewtwo'),
    (259, 'Pikachu ex', 'Pikachu'),
    (260, 'Zapdos ex', 'Pikachu'),
    (261, 'Gengar ex', 'Mewtwo'),
    (262, 'Mewtwo ex', 'Mewtwo'),
    (263, 'Machamp ex', 'Charizard'),
    (264, 'Marowak ex', 'Mewtwo'),
    (265, 'Wigglytuff ex', 'Pikachu'),
    (266, 'Erika', 'Charizard'),
    (267, 'Misty', 'Pikachu'),
    (268, 'Blaine', 'Charizard'),
    (269, 'Koga', 'Mewtwo'),
    (270, 'Giovanni', 'Mewtwo'),
    (271, 'Brock', 'Pikachu'),
    (272, 'Sabrina', 'Charizard'),
    (273, 'Lt. Surge', 'Pikachu'),
    (274, 'Moltres ex', 'Charizard'),
    (275, 'Articuno ex', 'Mewtwo'),
    (276, 'Zapdos ex', 'Pikachu'),
    (277, 'Gengar ex', 'Mewtwo'),
    (278, 'Machamp ex', 'Charizard'),
    (279, 'Wigglytuff ex', 'Pikachu'),
    (280, 'Charizard ex', 'Charizard'),
    (281, 'Pikachu ex', 'Pikachu'),
    (282, 'Mewtwo ex', 'Mewtwo'),
    (283, 'Mew', 'Shared'),
    (284, 'Charizard ex', 'Shared'),
    (285, 'Pikachu ex', 'Shared'),
    (286, 'Mewtwo ex', 'Shared')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
