-- Mythical Island (A1a) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A1a
-- Limitless lists Mythical Island as A1a with 86 cards.
-- Mythical Island has one booster pack, represented here as Mew.

insert into public.cards (id, name, pack, image)
select
  'A1a-' || lpad(card_number::text, 3, '0') as id,
  name,
  'Mew' as pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A1a/A1a_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Exeggcute'),
    (2, 'Exeggutor'),
    (3, 'Celebi ex'),
    (4, 'Snivy'),
    (5, 'Servine'),
    (6, 'Serperior'),
    (7, 'Morelull'),
    (8, 'Shiinotic'),
    (9, 'Dhelmise'),
    (10, 'Ponyta'),
    (11, 'Rapidash'),
    (12, 'Magmar'),
    (13, 'Larvesta'),
    (14, 'Volcarona'),
    (15, 'Salandit'),
    (16, 'Salazzle'),
    (17, 'Magikarp'),
    (18, 'Gyarados ex'),
    (19, 'Vaporeon'),
    (20, 'Finneon'),
    (21, 'Lumineon'),
    (22, 'Chewtle'),
    (23, 'Drednaw'),
    (24, 'Cramorant'),
    (25, 'Pikachu'),
    (26, 'Raichu'),
    (27, 'Electabuzz'),
    (28, 'Joltik'),
    (29, 'Galvantula'),
    (30, 'Dedenne'),
    (31, 'Mew'),
    (32, 'Mew ex'),
    (33, 'Sigilyph'),
    (34, 'Elgyem'),
    (35, 'Beheeyem'),
    (36, 'Flabébé'),
    (37, 'Floette'),
    (38, 'Florges'),
    (39, 'Swirlix'),
    (40, 'Slurpuff'),
    (41, 'Mankey'),
    (42, 'Primeape'),
    (43, 'Geodude'),
    (44, 'Graveler'),
    (45, 'Golem'),
    (46, 'Aerodactyl ex'),
    (47, 'Marshadow'),
    (48, 'Stonjourner'),
    (49, 'Koffing'),
    (50, 'Weezing'),
    (51, 'Purrloin'),
    (52, 'Liepard'),
    (53, 'Venipede'),
    (54, 'Whirlipede'),
    (55, 'Scolipede'),
    (56, 'Druddigon'),
    (57, 'Pidgey'),
    (58, 'Pidgeotto'),
    (59, 'Pidgeot ex'),
    (60, 'Tauros'),
    (61, 'Eevee'),
    (62, 'Chatot'),
    (63, 'Old Amber'),
    (64, 'Pokémon Flute'),
    (65, 'Mythical Slab'),
    (66, 'Budding Expeditioner'),
    (67, 'Blue'),
    (68, 'Leaf'),
    (69, 'Exeggutor'),
    (70, 'Serperior'),
    (71, 'Salandit'),
    (72, 'Vaporeon'),
    (73, 'Dedenne'),
    (74, 'Marshadow'),
    (75, 'Celebi ex'),
    (76, 'Gyarados ex'),
    (77, 'Mew ex'),
    (78, 'Aerodactyl ex'),
    (79, 'Pidgeot ex'),
    (80, 'Budding Expeditioner'),
    (81, 'Blue'),
    (82, 'Leaf'),
    (83, 'Mew ex'),
    (84, 'Aerodactyl ex'),
    (85, 'Celebi ex'),
    (86, 'Mew ex')
) as card_seed(card_number, name)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
