-- Shining Revelry (A2b) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A2b
-- Limitless lists Shining Revelry as A2b with 111 cards.
-- Shining Revelry has one booster pack, represented here as Shining Revelry.

insert into public.cards (id, name, pack, image)
select
  'A2b-' || lpad(card_number::text, 3, '0') as id,
  name,
  'Shining Revelry' as pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A2b/A2b_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Weedle'),
    (2, 'Kakuna'),
    (3, 'Beedrill ex'),
    (4, 'Pinsir'),
    (5, 'Sprigatito'),
    (6, 'Floragato'),
    (7, 'Meowscarada'),
    (8, 'Charmander'),
    (9, 'Charmeleon'),
    (10, 'Charizard ex'),
    (11, 'Magmar'),
    (12, 'Magmortar'),
    (13, 'Paldean Tauros'),
    (14, 'Tentacool'),
    (15, 'Tentacruel'),
    (16, 'Buizel'),
    (17, 'Floatzel'),
    (18, 'Wiglett'),
    (19, 'Wugtrio ex'),
    (20, 'Dondozo'),
    (21, 'Tatsugiri'),
    (22, 'Pikachu ex'),
    (23, 'Voltorb'),
    (24, 'Electrode'),
    (25, 'Pachirisu'),
    (26, 'Pawmi'),
    (27, 'Pawmo'),
    (28, 'Pawmot'),
    (29, 'Abra'),
    (30, 'Kadabra'),
    (31, 'Alakazam'),
    (32, 'Mr. Mime'),
    (33, 'Drifloon'),
    (34, 'Drifblim'),
    (35, 'Giratina ex'),
    (36, 'Gimmighoul'),
    (37, 'Machop'),
    (38, 'Machoke'),
    (39, 'Machamp'),
    (40, 'Hitmonlee'),
    (41, 'Hitmonchan'),
    (42, 'Riolu'),
    (43, 'Lucario ex'),
    (44, 'Flamigo'),
    (45, 'Ekans'),
    (46, 'Arbok'),
    (47, 'Paldean Wooper'),
    (48, 'Paldean Clodsire ex'),
    (49, 'Spiritomb'),
    (50, 'Shroodle'),
    (51, 'Grafaiai'),
    (52, 'Tinkatink'),
    (53, 'Tinkatuff'),
    (54, 'Tinkaton ex'),
    (55, 'Varoom'),
    (56, 'Revavroom'),
    (57, 'Gholdengo'),
    (58, 'Rattata'),
    (59, 'Raticate'),
    (60, 'Jigglypuff'),
    (61, 'Wigglytuff'),
    (62, 'Lickitung'),
    (63, 'Lickilicky'),
    (64, 'Bidoof'),
    (65, 'Bibarel ex'),
    (66, 'Buneary'),
    (67, 'Lopunny'),
    (68, 'Cyclizar'),
    (69, 'Iono'),
    (70, 'Pokémon Center Lady'),
    (71, 'Red'),
    (72, 'Team Rocket Grunt'),
    (73, 'Meowscarada'),
    (74, 'Buizel'),
    (75, 'Tatsugiri'),
    (76, 'Grafaiai'),
    (77, 'Gholdengo'),
    (78, 'Wigglytuff'),
    (79, 'Beedrill ex'),
    (80, 'Charizard ex'),
    (81, 'Wugtrio ex'),
    (82, 'Pikachu ex'),
    (83, 'Giratina ex'),
    (84, 'Lucario ex'),
    (85, 'Paldean Clodsire ex'),
    (86, 'Tinkaton ex'),
    (87, 'Bibarel ex'),
    (88, 'Iono'),
    (89, 'Pokémon Center Lady'),
    (90, 'Red'),
    (91, 'Team Rocket Grunt'),
    (92, 'Pikachu ex'),
    (93, 'Paldean Clodsire ex'),
    (94, 'Tinkaton ex'),
    (95, 'Bibarel ex'),
    (96, 'Giratina ex'),
    (97, 'Weedle'),
    (98, 'Kakuna'),
    (99, 'Charmander'),
    (100, 'Charmeleon'),
    (101, 'Wiglett'),
    (102, 'Dondozo'),
    (103, 'Pachirisu'),
    (104, 'Riolu'),
    (105, 'Varoom'),
    (106, 'Revavroom'),
    (107, 'Beedrill ex'),
    (108, 'Charizard ex'),
    (109, 'Wugtrio ex'),
    (110, 'Lucario ex'),
    (111, 'Poké Ball')
) as card_seed(card_number, name)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
