-- Eevee Grove (A3b) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/A3b
-- Limitless lists Eevee Grove as A3b with 107 cards.
-- Eevee Grove has one booster pack, represented here as Eevee Grove.

insert into public.cards (id, name, pack, image)
select
  'A3b-' || lpad(card_number::text, 3, '0') as id,
  name,
  'Eevee Grove' as pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/A3b/A3b_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Tropius'),
    (2, 'Leafeon'),
    (3, 'Bounsweet'),
    (4, 'Steenee'),
    (5, 'Tsareena'),
    (6, 'Applin'),
    (7, 'Appletun'),
    (8, 'Flareon'),
    (9, 'Flareon ex'),
    (10, 'Torkoal'),
    (11, 'Litten'),
    (12, 'Torracat'),
    (13, 'Incineroar'),
    (14, 'Salandit'),
    (15, 'Salazzle'),
    (16, 'Vaporeon'),
    (17, 'Glaceon'),
    (18, 'Vanillite'),
    (19, 'Vanillish'),
    (20, 'Vanilluxe'),
    (21, 'Alomomola'),
    (22, 'Popplio'),
    (23, 'Brionne'),
    (24, 'Primarina ex'),
    (25, 'Jolteon'),
    (26, 'Joltik'),
    (27, 'Galvantula'),
    (28, 'Espeon'),
    (29, 'Woobat'),
    (30, 'Swoobat'),
    (31, 'Swirlix'),
    (32, 'Slurpuff'),
    (33, 'Sylveon'),
    (34, 'Sylveon ex'),
    (35, 'Mimikyu'),
    (36, 'Milcery'),
    (37, 'Alcremie'),
    (38, 'Barboach'),
    (39, 'Whiscash'),
    (40, 'Mienfoo'),
    (41, 'Mienshao'),
    (42, 'Carbink'),
    (43, 'Umbreon'),
    (44, 'Sableye'),
    (45, 'Purrloin'),
    (46, 'Liepard'),
    (47, 'Mawile'),
    (48, 'Togedemaru'),
    (49, 'Meltan'),
    (50, 'Melmetal'),
    (51, 'Dratini'),
    (52, 'Dragonair'),
    (53, 'Dragonite ex'),
    (54, 'Drampa'),
    (55, 'Eevee'),
    (56, 'Eevee ex'),
    (57, 'Snorlax ex'),
    (58, 'Aipom'),
    (59, 'Ambipom'),
    (60, 'Chatot'),
    (61, 'Audino'),
    (62, 'Minccino'),
    (63, 'Cinccino'),
    (64, 'Skwovet'),
    (65, 'Greedent'),
    (66, 'Eevee Bag'),
    (67, 'Leftovers'),
    (68, 'Hau'),
    (69, 'Penny'),
    (70, 'Leafeon'),
    (71, 'Flareon'),
    (72, 'Vaporeon'),
    (73, 'Glaceon'),
    (74, 'Jolteon'),
    (75, 'Espeon'),
    (76, 'Sylveon'),
    (77, 'Umbreon'),
    (78, 'Eevee'),
    (79, 'Flareon ex'),
    (80, 'Primarina ex'),
    (81, 'Sylveon ex'),
    (82, 'Dragonite ex'),
    (83, 'Eevee ex'),
    (84, 'Snorlax ex'),
    (85, 'Hau'),
    (86, 'Penny'),
    (87, 'Flareon ex'),
    (88, 'Primarina ex'),
    (89, 'Sylveon ex'),
    (90, 'Dragonite ex'),
    (91, 'Snorlax ex'),
    (92, 'Eevee ex'),
    (93, 'Pinsir'),
    (94, 'Lapras'),
    (95, 'Voltorb'),
    (96, 'Electrode'),
    (97, 'Ralts'),
    (98, 'Kirlia'),
    (99, 'Gardevoir'),
    (100, 'Ekans'),
    (101, 'Arbok'),
    (102, 'Farfetch''d'),
    (103, 'Moltres ex'),
    (104, 'Articuno ex'),
    (105, 'Zapdos ex'),
    (106, 'Gallade ex'),
    (107, 'Eevee Bag')
) as card_seed(card_number, name)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
