-- Paldean Wonders (B2a) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B2a
-- Limitless lists Paldean Wonders as B2a with 131 cards.
-- Paldean Wonders has one booster pack, represented here as Paldean Wonders.

insert into public.cards (id, name, pack, image)
select
  'B2a-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2a/B2a_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Sprigatito', 'Paldean Wonders'),
    (2, 'Floragato', 'Paldean Wonders'),
    (3, 'Meowscarada ex', 'Paldean Wonders'),
    (4, 'Tarountula', 'Paldean Wonders'),
    (5, 'Spidops', 'Paldean Wonders'),
    (6, 'Nymble', 'Paldean Wonders'),
    (7, 'Smoliv', 'Paldean Wonders'),
    (8, 'Dolliv', 'Paldean Wonders'),
    (9, 'Arboliva', 'Paldean Wonders'),
    (10, 'Bramblin', 'Paldean Wonders'),
    (11, 'Brambleghast', 'Paldean Wonders'),
    (12, 'Capsakid', 'Paldean Wonders'),
    (13, 'Scovillain', 'Paldean Wonders'),
    (14, 'Rellor', 'Paldean Wonders'),
    (15, 'Wo-Chien', 'Paldean Wonders'),
    (16, 'Fuecoco', 'Paldean Wonders'),
    (17, 'Crocalor', 'Paldean Wonders'),
    (18, 'Skeledirge', 'Paldean Wonders'),
    (19, 'Charcadet', 'Paldean Wonders'),
    (20, 'Armarouge ex', 'Paldean Wonders'),
    (21, 'Chi-Yu', 'Paldean Wonders'),
    (22, 'Quaxly', 'Paldean Wonders'),
    (23, 'Quaxwell', 'Paldean Wonders'),
    (24, 'Quaquaval', 'Paldean Wonders'),
    (25, 'Wiglett', 'Paldean Wonders'),
    (26, 'Wugtrio', 'Paldean Wonders'),
    (27, 'Finizen', 'Paldean Wonders'),
    (28, 'Palafin', 'Paldean Wonders'),
    (29, 'Cetoddle', 'Paldean Wonders'),
    (30, 'Cetitan', 'Paldean Wonders'),
    (31, 'Veluza', 'Paldean Wonders'),
    (32, 'Dondozo', 'Paldean Wonders'),
    (33, 'Tatsugiri', 'Paldean Wonders'),
    (34, 'Frigibax', 'Paldean Wonders'),
    (35, 'Arctibax', 'Paldean Wonders'),
    (36, 'Baxcalibur', 'Paldean Wonders'),
    (37, 'Chien-Pao ex', 'Paldean Wonders'),
    (38, 'Pawmi', 'Paldean Wonders'),
    (39, 'Pawmo', 'Paldean Wonders'),
    (40, 'Pawmot', 'Paldean Wonders'),
    (41, 'Tadbulb', 'Paldean Wonders'),
    (42, 'Bellibolt ex', 'Paldean Wonders'),
    (43, 'Wattrel', 'Paldean Wonders'),
    (44, 'Kilowattrel', 'Paldean Wonders'),
    (45, 'Miraidon', 'Paldean Wonders'),
    (46, 'Fidough', 'Paldean Wonders'),
    (47, 'Dachsbun', 'Paldean Wonders'),
    (48, 'Ceruledge', 'Paldean Wonders'),
    (49, 'Rabsca', 'Paldean Wonders'),
    (50, 'Flittle', 'Paldean Wonders'),
    (51, 'Espathra', 'Paldean Wonders'),
    (52, 'Greavard', 'Paldean Wonders'),
    (53, 'Houndstone', 'Paldean Wonders'),
    (54, 'Gimmighoul', 'Paldean Wonders'),
    (55, 'Mankey', 'Paldean Wonders'),
    (56, 'Primeape', 'Paldean Wonders'),
    (57, 'Annihilape', 'Paldean Wonders'),
    (58, 'Paldean Tauros', 'Paldean Wonders'),
    (59, 'Toedscool', 'Paldean Wonders'),
    (60, 'Toedscruel', 'Paldean Wonders'),
    (61, 'Klawf', 'Paldean Wonders'),
    (62, 'Ting-Lu', 'Paldean Wonders'),
    (63, 'Koraidon', 'Paldean Wonders'),
    (64, 'Paldean Wooper', 'Paldean Wonders'),
    (65, 'Paldean Clodsire', 'Paldean Wonders'),
    (66, 'Lokix', 'Paldean Wonders'),
    (67, 'Maschiff', 'Paldean Wonders'),
    (68, 'Mabosstiff', 'Paldean Wonders'),
    (69, 'Shroodle', 'Paldean Wonders'),
    (70, 'Grafaiai', 'Paldean Wonders'),
    (71, 'Bombirdier', 'Paldean Wonders'),
    (72, 'Tinkatink', 'Paldean Wonders'),
    (73, 'Tinkatuff', 'Paldean Wonders'),
    (74, 'Tinkaton', 'Paldean Wonders'),
    (75, 'Varoom', 'Paldean Wonders'),
    (76, 'Revavroom', 'Paldean Wonders'),
    (77, 'Orthworm', 'Paldean Wonders'),
    (78, 'Gholdengo ex', 'Paldean Wonders'),
    (79, 'Lechonk', 'Paldean Wonders'),
    (80, 'Oinkologne', 'Paldean Wonders'),
    (81, 'Tandemaus', 'Paldean Wonders'),
    (82, 'Maushold', 'Paldean Wonders'),
    (83, 'Squawkabilly', 'Paldean Wonders'),
    (84, 'Cyclizar', 'Paldean Wonders'),
    (85, 'Flamigo', 'Paldean Wonders'),
    (86, 'Electric Generator', 'Paldean Wonders'),
    (87, 'Big Air Balloon', 'Paldean Wonders'),
    (88, 'Team Star Grunt', 'Paldean Wonders'),
    (89, 'Iono', 'Paldean Wonders'),
    (90, 'Nemona', 'Paldean Wonders'),
    (91, 'Arven', 'Paldean Wonders'),
    (92, 'Penny', 'Paldean Wonders'),
    (93, 'Mesagoza', 'Paldean Wonders'),
    (94, 'Fuecoco', 'Paldean Wonders'),
    (95, 'Greavard', 'Paldean Wonders'),
    (96, 'Gimmighoul', 'Paldean Wonders'),
    (97, 'Paldean Wooper', 'Paldean Wonders'),
    (98, 'Orthworm', 'Paldean Wonders'),
    (99, 'Maushold', 'Paldean Wonders'),
    (100, 'Meowscarada ex', 'Paldean Wonders'),
    (101, 'Armarouge ex', 'Paldean Wonders'),
    (102, 'Chien-Pao ex', 'Paldean Wonders'),
    (103, 'Bellibolt ex', 'Paldean Wonders'),
    (104, 'Gholdengo ex', 'Paldean Wonders'),
    (105, 'Team Star Grunt', 'Paldean Wonders'),
    (106, 'Iono', 'Paldean Wonders'),
    (107, 'Nemona', 'Paldean Wonders'),
    (108, 'Arven', 'Paldean Wonders'),
    (109, 'Penny', 'Paldean Wonders'),
    (110, 'Meowscarada ex', 'Paldean Wonders'),
    (111, 'Armarouge ex', 'Paldean Wonders'),
    (112, 'Chien-Pao ex', 'Paldean Wonders'),
    (113, 'Bellibolt ex', 'Paldean Wonders'),
    (114, 'Gholdengo ex', 'Paldean Wonders'),
    (115, 'Arven', 'Paldean Wonders'),
    (116, 'Sprigatito', 'Paldean Wonders'),
    (117, 'Floragato', 'Paldean Wonders'),
    (118, 'Meowscarada', 'Paldean Wonders'),
    (119, 'Pawmi', 'Paldean Wonders'),
    (120, 'Pawmo', 'Paldean Wonders'),
    (121, 'Pawmot', 'Paldean Wonders'),
    (122, 'Gimmighoul', 'Paldean Wonders'),
    (123, 'Tinkatink', 'Paldean Wonders'),
    (124, 'Tinkatuff', 'Paldean Wonders'),
    (125, 'Gholdengo', 'Paldean Wonders'),
    (126, 'Entei ex', 'Paldean Wonders'),
    (127, 'Suicune ex', 'Paldean Wonders'),
    (128, 'Raikou ex', 'Paldean Wonders'),
    (129, 'Tinkaton ex', 'Paldean Wonders'),
    (130, 'Baxcalibur', 'Paldean Wonders'),
    (131, 'Electric Generator', 'Paldean Wonders')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
