-- Mega Shine (B2b) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B2b
-- Limitless lists Mega Shine as B2b with 117 cards.
-- Mega Shine has one booster pack, represented here as Mega Shine.

insert into public.cards (id, name, pack, image)
select
  'B2b-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B2b/B2b_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Scyther', 'Mega Shine'),
    (2, 'Pineco', 'Mega Shine'),
    (3, 'Volbeat', 'Mega Shine'),
    (4, 'Illumise', 'Mega Shine'),
    (5, 'Phantump', 'Mega Shine'),
    (6, 'Trevenant', 'Mega Shine'),
    (7, 'Charmander', 'Mega Shine'),
    (8, 'Charmeleon', 'Mega Shine'),
    (9, 'Mega Charizard X ex', 'Mega Shine'),
    (10, 'Ponyta', 'Mega Shine'),
    (11, 'Rapidash', 'Mega Shine'),
    (12, 'Magmar', 'Mega Shine'),
    (13, 'Magmortar', 'Mega Shine'),
    (14, 'Paldean Tauros', 'Mega Shine'),
    (15, 'Slowpoke', 'Mega Shine'),
    (16, 'Mega Slowbro ex', 'Mega Shine'),
    (17, 'Lapras', 'Mega Shine'),
    (18, 'Piplup', 'Mega Shine'),
    (19, 'Prinplup', 'Mega Shine'),
    (20, 'Empoleon', 'Mega Shine'),
    (21, 'Phione', 'Mega Shine'),
    (22, 'Pikachu', 'Mega Shine'),
    (23, 'Raichu', 'Mega Shine'),
    (24, 'Electabuzz', 'Mega Shine'),
    (25, 'Electivire', 'Mega Shine'),
    (26, 'Electrike', 'Mega Shine'),
    (27, 'Mega Manectric ex', 'Mega Shine'),
    (28, 'Drowzee', 'Mega Shine'),
    (29, 'Hypno', 'Mega Shine'),
    (30, 'Mew', 'Mega Shine'),
    (31, 'Spoink', 'Mega Shine'),
    (32, 'Grumpig', 'Mega Shine'),
    (33, 'Diglett', 'Mega Shine'),
    (34, 'Dugtrio', 'Mega Shine'),
    (35, 'Groudon', 'Mega Shine'),
    (36, 'Hawlucha', 'Mega Shine'),
    (37, 'Gastly', 'Mega Shine'),
    (38, 'Haunter', 'Mega Shine'),
    (39, 'Mega Gengar ex', 'Mega Shine'),
    (40, 'Darkrai', 'Mega Shine'),
    (41, 'Trubbish', 'Mega Shine'),
    (42, 'Garbodor', 'Mega Shine'),
    (43, 'Zorua', 'Mega Shine'),
    (44, 'Zoroark', 'Mega Shine'),
    (45, 'Morpeko', 'Mega Shine'),
    (46, 'Forretress', 'Mega Shine'),
    (47, 'Mega Scizor ex', 'Mega Shine'),
    (48, 'Kartana', 'Mega Shine'),
    (49, 'Varoom', 'Mega Shine'),
    (50, 'Revavroom', 'Mega Shine'),
    (51, 'Dratini', 'Mega Shine'),
    (52, 'Dragonair', 'Mega Shine'),
    (53, 'Dragonite', 'Mega Shine'),
    (54, 'Axew', 'Mega Shine'),
    (55, 'Fraxure', 'Mega Shine'),
    (56, 'Haxorus', 'Mega Shine'),
    (57, 'Druddigon', 'Mega Shine'),
    (58, 'Jigglypuff', 'Mega Shine'),
    (59, 'Wigglytuff', 'Mega Shine'),
    (60, 'Miltank', 'Mega Shine'),
    (61, 'Chatot', 'Mega Shine'),
    (62, 'Minccino', 'Mega Shine'),
    (63, 'Cinccino', 'Mega Shine'),
    (64, 'Furfrou', 'Mega Shine'),
    (65, 'Nasty Notice', 'Mega Shine'),
    (66, 'Maintenance', 'Mega Shine'),
    (67, 'Iris', 'Mega Shine'),
    (68, 'Calem', 'Mega Shine'),
    (69, 'Hiking Trail', 'Mega Shine'),
    (70, 'Lapras', 'Mega Shine'),
    (71, 'Empoleon', 'Mega Shine'),
    (72, 'Groudon', 'Mega Shine'),
    (73, 'Morpeko', 'Mega Shine'),
    (74, 'Revavroom', 'Mega Shine'),
    (75, 'Miltank', 'Mega Shine'),
    (76, 'Mega Charizard X ex', 'Mega Shine'),
    (77, 'Mega Slowbro ex', 'Mega Shine'),
    (78, 'Mega Manectric ex', 'Mega Shine'),
    (79, 'Mega Gengar ex', 'Mega Shine'),
    (80, 'Mega Scizor ex', 'Mega Shine'),
    (81, 'Iris', 'Mega Shine'),
    (82, 'Calem', 'Mega Shine'),
    (83, 'Mega Slowbro ex', 'Mega Shine'),
    (84, 'Mega Manectric ex', 'Mega Shine'),
    (85, 'Mew', 'Mega Shine'),
    (86, 'Mew', 'Mega Shine'),
    (87, 'Scyther', 'Mega Shine'),
    (88, 'Pineco', 'Mega Shine'),
    (89, 'Phantump', 'Mega Shine'),
    (90, 'Trevenant', 'Mega Shine'),
    (91, 'Charmander', 'Mega Shine'),
    (92, 'Charmeleon', 'Mega Shine'),
    (93, 'Ponyta', 'Mega Shine'),
    (94, 'Rapidash', 'Mega Shine'),
    (95, 'Slowpoke', 'Mega Shine'),
    (96, 'Pikachu', 'Mega Shine'),
    (97, 'Raichu', 'Mega Shine'),
    (98, 'Electrike', 'Mega Shine'),
    (99, 'Hawlucha', 'Mega Shine'),
    (100, 'Gastly', 'Mega Shine'),
    (101, 'Haunter', 'Mega Shine'),
    (102, 'Zorua', 'Mega Shine'),
    (103, 'Zoroark', 'Mega Shine'),
    (104, 'Forretress', 'Mega Shine'),
    (105, 'Dratini', 'Mega Shine'),
    (106, 'Dragonair', 'Mega Shine'),
    (107, 'Dragonite', 'Mega Shine'),
    (108, 'Axew', 'Mega Shine'),
    (109, 'Fraxure', 'Mega Shine'),
    (110, 'Haxorus', 'Mega Shine'),
    (111, 'Mega Charizard X ex', 'Mega Shine'),
    (112, 'Mega Slowbro ex', 'Mega Shine'),
    (113, 'Mega Manectric ex', 'Mega Shine'),
    (114, 'Mega Gengar ex', 'Mega Shine'),
    (115, 'Mega Scizor ex', 'Mega Shine'),
    (116, 'Arboliva', 'Mega Shine'),
    (117, 'Metal Core Barrier', 'Mega Shine')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
