-- Everyday Wonders (B3b) cards seed data for public.cards.
-- Source: https://pocket.limitlesstcg.com/cards/B3b
-- Limitless lists Everyday Wonders as B3b with 106 cards.
-- Everyday Wonders has one booster pack, represented here as Everyday Wonders.

insert into public.cards (id, name, pack, image)
select
  'B3b-' || lpad(card_number::text, 3, '0') as id,
  name,
  pack,
  'https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/B3b/B3b_' || lpad(card_number::text, 3, '0') || '_EN.png' as image
from (
  values
    (1, 'Caterpie', 'Everyday Wonders'),
    (2, 'Metapod', 'Everyday Wonders'),
    (3, 'Butterfree', 'Everyday Wonders'),
    (4, 'Cacnea', 'Everyday Wonders'),
    (5, 'Tropius', 'Everyday Wonders'),
    (6, 'Petilil', 'Everyday Wonders'),
    (7, 'Hisuian Lilligant', 'Everyday Wonders'),
    (8, 'Vulpix', 'Everyday Wonders'),
    (9, 'Ninetales', 'Everyday Wonders'),
    (10, 'Growlithe', 'Everyday Wonders'),
    (11, 'Psyduck', 'Everyday Wonders'),
    (12, 'Goldeen', 'Everyday Wonders'),
    (13, 'Seaking', 'Everyday Wonders'),
    (14, 'Feebas', 'Everyday Wonders'),
    (15, 'Milotic ex', 'Everyday Wonders'),
    (16, 'Snorunt', 'Everyday Wonders'),
    (17, 'Froslass', 'Everyday Wonders'),
    (18, 'Luvdisc', 'Everyday Wonders'),
    (19, 'Piplup', 'Everyday Wonders'),
    (20, 'Iron Bundle', 'Everyday Wonders'),
    (21, 'Pikachu', 'Everyday Wonders'),
    (22, 'Raichu', 'Everyday Wonders'),
    (23, 'Emolga', 'Everyday Wonders'),
    (24, 'Dedenne ex', 'Everyday Wonders'),
    (25, 'Yamper', 'Everyday Wonders'),
    (26, 'Slowpoke', 'Everyday Wonders'),
    (27, 'Slowbro', 'Everyday Wonders'),
    (28, 'Munna', 'Everyday Wonders'),
    (29, 'Musharna', 'Everyday Wonders'),
    (30, 'Sylveon', 'Everyday Wonders'),
    (31, 'Carbink', 'Everyday Wonders'),
    (32, 'Mega Diancie ex', 'Everyday Wonders'),
    (33, 'Enamorus', 'Everyday Wonders'),
    (34, 'Fidough', 'Everyday Wonders'),
    (35, 'Flutter Mane', 'Everyday Wonders'),
    (36, 'Wooper', 'Everyday Wonders'),
    (37, 'Quagsire', 'Everyday Wonders'),
    (38, 'Rockruff', 'Everyday Wonders'),
    (39, 'Sandygast', 'Everyday Wonders'),
    (40, 'Palossand', 'Everyday Wonders'),
    (41, 'Mega Sableye ex', 'Everyday Wonders'),
    (42, 'Cacturne', 'Everyday Wonders'),
    (43, 'Spiritomb', 'Everyday Wonders'),
    (44, 'Scraggy', 'Everyday Wonders'),
    (45, 'Scrafty', 'Everyday Wonders'),
    (46, 'Mareanie', 'Everyday Wonders'),
    (47, 'Toxapex', 'Everyday Wonders'),
    (48, 'Goomy', 'Everyday Wonders'),
    (49, 'Hisuian Sliggoo', 'Everyday Wonders'),
    (50, 'Hisuian Goodra', 'Everyday Wonders'),
    (51, 'Jigglypuff', 'Everyday Wonders'),
    (52, 'Wigglytuff', 'Everyday Wonders'),
    (53, 'Eevee', 'Everyday Wonders'),
    (54, 'Munchlax', 'Everyday Wonders'),
    (55, 'Snorlax', 'Everyday Wonders'),
    (56, 'Teddiursa', 'Everyday Wonders'),
    (57, 'Ursaring', 'Everyday Wonders'),
    (58, 'Ursaluna', 'Everyday Wonders'),
    (59, 'Hisuian Zorua', 'Everyday Wonders'),
    (60, 'Hisuian Zoroark ex', 'Everyday Wonders'),
    (61, 'Furfrou', 'Everyday Wonders'),
    (62, 'Skwovet', 'Everyday Wonders'),
    (63, 'Greedent', 'Everyday Wonders'),
    (64, 'Small Balloon', 'Everyday Wonders'),
    (65, 'Elegant Cape', 'Everyday Wonders'),
    (66, 'Elesa', 'Everyday Wonders'),
    (67, 'Puppy-Loving Girl', 'Everyday Wonders'),
    (68, 'Wallace', 'Everyday Wonders'),
    (69, 'Kid''s Room', 'Everyday Wonders'),
    (70, 'Vulpix', 'Everyday Wonders'),
    (71, 'Piplup', 'Everyday Wonders'),
    (72, 'Pikachu', 'Everyday Wonders'),
    (73, 'Sylveon', 'Everyday Wonders'),
    (74, 'Mareanie', 'Everyday Wonders'),
    (75, 'Jigglypuff', 'Everyday Wonders'),
    (76, 'Snorlax', 'Everyday Wonders'),
    (77, 'Greedent', 'Everyday Wonders'),
    (78, 'Milotic ex', 'Everyday Wonders'),
    (79, 'Dedenne ex', 'Everyday Wonders'),
    (80, 'Mega Diancie ex', 'Everyday Wonders'),
    (81, 'Mega Sableye ex', 'Everyday Wonders'),
    (82, 'Hisuian Zoroark ex', 'Everyday Wonders'),
    (83, 'Elesa', 'Everyday Wonders'),
    (84, 'Puppy-Loving Girl', 'Everyday Wonders'),
    (85, 'Wallace', 'Everyday Wonders'),
    (86, 'Milotic ex', 'Everyday Wonders'),
    (87, 'Mega Diancie ex', 'Everyday Wonders'),
    (88, 'Mega Sableye ex', 'Everyday Wonders'),
    (89, 'Hisuian Zoroark ex', 'Everyday Wonders'),
    (90, 'Dedenne ex', 'Everyday Wonders'),
    (91, 'Caterpie', 'Everyday Wonders'),
    (92, 'Metapod', 'Everyday Wonders'),
    (93, 'Butterfree', 'Everyday Wonders'),
    (94, 'Mareep', 'Everyday Wonders'),
    (95, 'Flaaffy', 'Everyday Wonders'),
    (96, 'Ampharos', 'Everyday Wonders'),
    (97, 'Slowbro', 'Everyday Wonders'),
    (98, 'Kangaskhan', 'Everyday Wonders'),
    (99, 'Ditto', 'Everyday Wonders'),
    (100, 'Snorlax', 'Everyday Wonders'),
    (101, 'Mega Gyarados ex', 'Everyday Wonders'),
    (102, 'Vaporeon ex', 'Everyday Wonders'),
    (103, 'Mega Ampharos ex', 'Everyday Wonders'),
    (104, 'Indeedee ex', 'Everyday Wonders'),
    (105, 'Munchlax', 'Everyday Wonders'),
    (106, 'Small Balloon', 'Everyday Wonders')
) as card_seed(card_number, name, pack)
on conflict (id) do update set
  name = excluded.name,
  pack = excluded.pack,
  image = excluded.image;
